### ISSUE TITLE
data field name missing

### ISSUE THREAD

**Issue by brusand** [kongchen/swagger-maven-plugin#112]
Hi 

I don t know if it is a bug or a misunderstood but for the generated data types, the field name is not printed ? how can print them (like swagger)
Thx
Bruno

CompanyInformation
type 	required 	access 	description 	notes
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-
string 	optional 	- 	- 	-

**Comment by kongchen** [comment]
The template file missed it, thanks for the finding.

**Comment by kongchen** [comment]
2.3.4-SNAPSHOT fixes the issue.
