### ISSUE TITLE
ApiModel value attribute not used to rename model

### ISSUE THREAD

**Issue by davetroiano** [kongchen/swagger-maven-plugin#113]
The @ApiModel annotation has a value attribute that can be used to provide an alternative model name for a class.  It appears that the swagger-maven-plugin doesn't support this.  To repro, take the swagger-maven-example project and annotate the Category class with @ApiModel(value="RenamedCategory").  The desired generated pet.json would be for models.Category.id to be RenamedCategory, but it remains Category.

Is this known / intended?

**Comment by kongchen** [comment]
It's a bug of swagger-core. check here: https://github.com/swagger-api/swagger-core/issues/642
The bug is only fixed in dev2.0 branch - the swagger 2.0 spec - is not compatibled with swagger spec 1.2 which you're using.
For your purpose, here's another workaround:
```
@XmlRootElement(name = "RenamedCategory")
public class Category {
```
