### ISSUE TITLE
classes used as subType don't pull in referenced type information. 

### ISSUE THREAD

**Issue by ockernuts** [kongchen/swagger-maven-plugin#114]
when using a "base class" A with derived B (by means of specifying @ApiModel(parent=A.class) on B and @ApiModel(subtypes= { B.class })
and where B has a property using type C, then in the outputted Swagger json, the B type is described and references for the property correctly type C, but the C type is not described in the outputted Swagger json. 
This only gets detected when the type C is a "non-trivial" type that is not known already through other paths.

**Comment by kongchen** [comment]
check here: https://github.com/swagger-api/swagger-core/issues/563 , same issue?
