### ISSUE TITLE
@ApiImplicitParams It doesn’t generate the implicit parameter values to jason 

### ISSUE THREAD

**Issue by mortias** [kongchen/swagger-maven-plugin#119]
@ApiImplicitParams(value = {
            @ApiImplicitParam(name = "a", value = "ID", required = true, dataType = "string", paramType = "header", defaultValue = "a"),
            @ApiImplicitParam(name = "b", value = "User's language", required = true, dataType = "string", paramType = "header", defaultValue = "b"),
            @ApiImplicitParam(name = "c", value = "User's IP Address", required = true, dataType = "string", paramType = "header", defaultValue = "c")
    })

when you use the @ApiImplicitParams tags they are not converted to json parameters:

    "parameters" : [ {
        "name" : "a",
        "description" : "ID",
        "defaultValue" : "a",
        "required" : true,
        "type" : "string",
        "paramType" : "header",
        "allowMultiple" : false
      }, {
        "name" : "b",
        "description" : "User's language",
        "defaultValue" : "b",
        "required" : true,
        "type" : "string",
        "paramType" : "header",
        "allowMultiple" : false
      }, {
        "name" : "c",
        "description" : "User's IP Address",
        "defaultValue" : "c",
        "required" : true,
        "type" : "string",
        "paramType" : "header",
        "allowMultiple" : false
      } ],

**Comment by kongchen** [comment]
which version do you use? 2.3.3 or 3.0.0-SNAPSHOT? which mode do you use? springMVC or not?

**Comment by mortias** [comment]
The 3.0 not spring version..


Verzonden vanaf mijn Samsung Galaxy smartphone.


-------- Oorspronkelijk bericht --------
Van: Yukai Kong <notifications@github.com> 
Datum:15-03-2015  14:44  (GMT+01:00) 
Aan: kongchen/swagger-maven-plugin <swagger-maven-plugin@noreply.github.com> 
Cc: Mortier Andries <mortier@telenet.be> 
Onderwerp: Re: [swagger-maven-plugin] @ApiImplicitParams It doesn’t generate the implicit parameter values to jason  (#119) 

which version do you use? 2.3.3 or 3.0.0-SNAPSHOT? which mode do you use? springMVC or not?

**Comment by mortias** [comment]
probably related to https://github.com/swagger-api/swagger-core/issues/905

**Comment by who** [comment]
@mortias I just committed support for ApiImplicitParams. Could you please try again ?
