### ISSUE TITLE
3.0 (alpha/beta) release in maven central?

### ISSUE THREAD

**Issue by typekpb** [kongchen/swagger-maven-plugin#121]
Is there a chance to have 3.0 relase (maybe some alpha/beta in maven central) in the near future? As there seems to be many changes on the master, as compared to dev2.0 branch that sound like need to be merged.

I'd like to document Maps, that is however possible with Swagger 2.0 specs only (https://github.com/swagger-api/swagger-spec/issues/38) but in the meantime have all the fixes from the master.

**Comment by kongchen** [comment]
Yes, 3.0 is totally different from 2.x due to big changes in swagger core itself, and 3.0 does not support springmvc either. So there will no merge.

I can have a alpha release for 3.0 in one or two days, will let you know by then.

**Comment by typekpb** [comment]
Ok, thanks!

**Comment by kongchen** [comment]
[3.0-M1](http://search.maven.org/#artifactdetails%7Ccom.github.kongchen%7Cswagger-maven-plugin%7C3.0-M1%7Cmaven-plugin) is released.

**Comment by typekpb** [comment]
Thanks
