### ISSUE TITLE
is it possible to catch grouped parameters ?

### ISSUE THREAD

**Issue by mortias** [kongchen/swagger-maven-plugin#122]
so i would like to have something like this..  
then you annotate your @Get with this @SwaggerDefaults(headers = true, responses = true)

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD) //can use in method only.
@Inherited
public @interface SwaggerDefaults {

    @ApiImplicitParams(value = {
            @ApiImplicitParam(name = "a", value = "a", required = true, dataType = "string", paramType = "header", defaultValue = "a"),
            @ApiImplicitParam(name = "a", value = "a", required = true, dataType = "string", paramType = "header", defaultValue = "a"),
            @ApiImplicitParam(name = "a", value = "a", required = true, dataType = "string", paramType = "header", defaultValue = "a"),
    })
    boolean headers() default false;

    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "The request returned a valid response."),

            @ApiResponse(code = 204, message = "No content or data found"),
            @ApiResponse(code = 400, message = "Bad request"),
            @ApiResponse(code = 500, message = "Internal server error")})

    boolean responses() default false;

}

**Comment by kongchen** [comment]
I think you can take this idea to swagger-core group, this plugin only supports what swagger-core supports.
Thanks.
