### ISSUE TITLE
can I process multiple maven projects?

### ISSUE THREAD

**Issue by hongxingli** [kongchen/swagger-maven-plugin#126]
hi Chen Kong,

In our project, we have 
main/src/user-api/src/main/java 
main/src/account-api/src/main/java 
......

two question, we can generate a single html and json for all those projects? Right now, it seems generate a json file for each resource.java, do we have a way to automatically merge them together?
Thanks,
Hongxing

**Comment by kongchen** [comment]
You mean you'd like to merge the json files into one? Why do so? It would broke swagger's style.

**Comment by hongxingli** [comment]
Thanks, that makes sense.

How about resource across multiple projects? as of now, I run the plugin in each project and it will generate multiple html files and multiple service.json files, do we have a way to auto merge them?

**Comment by kongchen** [comment]
Sorry, I've no ideas.

**Comment by prkarthikeyan** [comment]
Hey, how do i create a single swagger across multiple modules. I have a parent pom.xml with modules and each holding a pom.xml. If i configure the plugin at parent pom.xml this seems to not pick the package locations provided. Giving at each modules produces multiple files, how to merge these files or make a single swagger for the entire project with multiple modules??

**Comment by prkarthikeyan** [comment]
@kongchen , please help with your thoughts on this.

**Comment by StNekroman** [comment]
the same problem

**Comment by StNekroman** [comment]
Very important bug, which is closed somewhy
