### ISSUE TITLE
Using version 2.3.3 creates the same file name for each method, so only the last method is exported.

### ISSUE THREAD

**Issue by websusk** [kongchen/swagger-maven-plugin#129]
Plugin version 2.3.3.  When I run "mvn clean compile" I get the following ouput...

[INFO] Reflections took 45 ms to scan 1 urls, producing 5 keys and 6 values 
[INFO] Creating file /resources/api-docs/service.json
[INFO] Creating file /resources/api-docs/asr.json
[INFO] Creating file /resources/api-docs/asr.json

...so only the last method is documented inside the /asr module as the file just overwrites the previous one...

**Comment by mteodori** [comment]
is this with springmvc support? I get the same there

**Comment by websusk** [comment]
Sorry,  should have mentioned that.  Yes,  I am using supportSpringMvc as true.

**Comment by kongchen** [comment]
It should be a bug, I'll look into. Thanks.

**Comment by kvelakur** [comment]
I've reported the same bug, its issue #120 . It happens with both 2.3.3 and 2.3.4. 

Temporary workaround: when 2.3.3 is used with supportSpringMvc set to false, the plugin does not throw an NPE and produces some kind of an output. But it does not work as expected and needs to be fixed. 

@kongchen I can try help fix this issue, could you point me to the relevant code that I need to look at?

**Comment by kongchen** [comment]
@kvelakur Thanks, you can look at `com.github.kongchen.swagger.docgen.spring.SpringMvcApiReader` or tell me how you configure your controller.

**Comment by kongchen** [comment]
Would you please try version 3.0.0 and tell me if it stills an issue?
