### ISSUE TITLE
How to get rid of the wrapper classes in json?

### ISSUE THREAD

**Issue by mortias** [kongchen/swagger-maven-plugin#131]
Hello,

I've seen this issue before without any solution, 
the question is how to get rid of the wrapper classes in the generated json documentation?

ex.: a BigDecimal generates this : 

AAAA {
 value (BigDecimal, optional),
}

BigDecimal {
 scale (integer, optional),
 precision (integer, optional)
}

using swagger 1.3.2 specs

tx

**Comment by kongchen** [comment]
Try to use swagger-overriding-models.json

**Comment by kongchen** [comment]
Please try to use `3.0.0+`
