### ISSUE TITLE
SpringMvc support for swagger spec 2.0

### ISSUE THREAD

**Issue by Richou** [kongchen/swagger-maven-plugin#133]
Hello,

For a project, I really need the Spring MVC support for swagger spec 2.0. So I would like to know when do you plan to add this support on your swagger maven plugin ?

Thanks for your answer and your work.
Regards.

**Comment by kongchen** [comment]
in this month.

**Comment by Richou** [comment]
Great ! Thanks a lot !

**Comment by typekpb** [comment]
+1

**Comment by kongchen** [comment]
Hi all, I just release `3.0-M2-SNAPSHOT`which supports SpringMvc, could you please have a try and give any feedback?

**Comment by kongchen** [comment]
Please note that **`1.5.1-M2`** is the official version for swagger spec 2.0.

**Comment by Richou** [comment]
Thanks a lot ! I will try as soon as possible.

**Comment by Richou** [comment]
I tried the springmvc support and it work very well so far. 
I will let you know if I encounter some problems.

Thanks again for your work.
