### ISSUE TITLE
3.0-M1 @ApiParam(required = true...) ignored

### ISSUE THREAD

**Issue by typekpb** [kongchen/swagger-maven-plugin#136]
Following:

    @ApiParam(value = "foo stuff", required = true, allowMultiple = true) @QueryParam("foo") List<String> foo)

results in: 

        ...
	"parameters" : [ {
          "name" : "foo",
          "in" : "query",
          "description" : "foo stuff",
          "required" : false,
          "type" : "array",
          "collectionFormat" : "multi"
        } ],

however it should be:

        ...
	"parameters" : [ {
          "name" : "foo",
          "in" : "query",
          "description" : "foo stuff",
          "required" : true,
          "type" : "array",
          "collectionFormat" : "multi"
        } ],

**Comment by kongchen** [comment]
Thanks, I've fixed the issue but not pushed, will do that soon, which includes springmvc support.

**Comment by typekpb** [comment]
@kongchen sounds like a dream, thanks!
