### ISSUE TITLE
3.0-M1 `@ApiParam(allowMultiple = true...) List<String> foo` doesn't generate the: `,"items":{"type":"string"}` part

### ISSUE THREAD

**Issue by typekpb** [kongchen/swagger-maven-plugin#137]
Following:

    @ApiParam(value = "foo stuff", required = true, allowMultiple = true) @QueryParam("foo") List<String> foo)

results in: 

        ...
	"parameters" : [ {
          "name" : "foo",
          "in" : "query",
          "description" : "foo stuff",
          "required" : false,
          "type" : "array",
          "collectionFormat" : "multi"
        } ],

however it should be:

        ...
	 "parameters" : [ {
          "name" : "foo",
          "in" : "query",
          "description" : "foo stuff",
          "required" : false,
          "type" : "array",
	  "items":{"type":"string"},
          "collectionFormat" : "multi"
        } ],

(please note that the ignored required attribute problem is tracked elsewhere, in: #136 )

The motivation behind issue is, that otherwise supplying multiple values in the swagger UI in a comma separated way doesn't work, as whatever is typed is sent as a single value (rather than list of values).

**Comment by typekpb** [comment]
or is there something missing in my annotation, that would refer to items type (`string` in this case)?

**Comment by kongchen** [comment]
How about define your API like this: (paste from swagger example)
```
@GET
  @Path("/findByTags")
  @ApiOperation(value = "Finds Pets by tags",
          notes = "Muliple tags can be provided with comma seperated strings. Use tag1, tag2, tag3 for testing.",
          response = Pet.class,
          responseContainer = "List")
  @ApiResponses(value = {@ApiResponse(code = 400, message = "Invalid tag value")})
  @Deprecated
  public Response findPetsByTags(
          @ApiParam(value = "Tags to filter by", required = true, allowMultiple = true) @QueryParam("tags") String tags) {
    return Response.ok(petData.findPetByTags(tags)).build();
  }
```

**Comment by typekpb** [comment]
Well, that could work, however we're trying to keep our REST API as it is and just document it with the swagger. So it doesn't really fit our requirements.

Any chance to provide support in the maven plugin for the `List<String> foo`? Otherwise I'd just need to hack the generated json file somehow (which I try to prevent).

**Comment by kongchen** [comment]
Even you can output the swagger.json like you said, it is still difficult for the people who reads the document to know what is the delimiter.

I recall that when you use `@QueryParam("q") List<String> qList` in jersey, it will collect all of the values whose names are `q` and put them together to the list.
> e.g. assume the url is something like `?q=1&a=2&q=3&q=4`, you'll get a list `qList = ["1","3","4"]`

**Comment by typekpb** [comment]
your assumption on sample url is correct.

regarding not- intuitive way, well, I guess you're right, but that's the way it is for us right now.

btw if you check the officially referred swagger-ui json (from petstore), it uses it: http://petstore.swagger.io/v2/swagger.json, you'll find this way in use, just search for: `,"description":"Multiple status values can be provided with comma seperated strings"` 

That is the place that gave me the impression that I have a chance to do it, just maven plugin misses support for that one.

**Comment by kongchen** [comment]
Thanks for the link, l'll look into to see how the swagger.json generates.

**Comment by typekpb** [comment]
perfect, thanks!

**Comment by kongchen** [comment]
I check the samples [here](https://github.com/swagger-api/swagger-core/blob/master/samples/java-jersey-jaxrs/src/main/java/com/wordnik/swagger/sample/resource/PetResource.java#L144)
`allowMultiple = true` will let swagger reader outputs as you expect:
```
"type" : "array",
  "items":{"type":"string"}
```

**Comment by who** [comment]
@kongchen 

I face the same issue as @typekpb. The SpringMVC app I am working in must use `@RequestParam List<String> foo`, so I made the change and submitted a PR : https://github.com/kongchen/swagger-maven-plugin/pull/151

Essentially, the problem was that when List<T>, Set<T>, etc was used in a `@RequestParam`, the SpringSwaggerExtension was not persisting the type of sub-items as `"string"`.
