### ISSUE TITLE
How are top-level securityDefinitions defined?

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#139]
It appears that there is no way to define a securityDefinition at the root level. 

This ApiOperation ... 

```
@RestController
@RequestMapping("/test")
@Api(value = "test")
public class test{
    @RequestMapping(
        value = "/testing", 
        method = RequestMethod.GET, 
        produces = MediaType.TEXT_PLAIN_VALUE)
    @ApiOperation(
        value = "testing",
        authorizations = @Authorization(value = "basicAuth", type = "basicAuth")
    )
    public String testMethod() {
        return "testing";
    }
}
```

... yields this json ...

```
  "paths" : {
    "/test/testing" : {
      "get" : {
        "tags" : [ "test" ],
        "summary" : "testing",
        "description" : "",
        "operationId" : "testMethod",
        "produces" : [ "text/plain" ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "string"
            }
          }
        },
        "security" : [ {
          "basicAuth" : [ ]
        } ]
      }
    }
  }
```

However, there is no `securityDefinition` defined at the root level, so the spec is not valid. 

Here is the relevant section in the Swagger 2.0 spec definition: https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#security-definitions-object

**Comment by kongchen** [comment]
There's no corresponding annotations to do that, do you have any good ideas for that info? 
My intuition is to provide a separate json file to define the `securityDefinition` and configure its path in pom.xml.

**Comment by who** [comment]
I think an external JSON file would work well for complex securityDefinitions, but it would also be nice to be able to define this inside the apiSource node of the plugin xml.  For more basic securtyDefinitions, only two strings (name, type) are needed.  

I propose something flexible, like so:

```
<apiSource>
...
    <securityDefinitions>
        <securityDefinition name="basicAuth" type="basic" />
        <securityDefinition>/path/to/securityDefinition.json</securityDefinition>
    </securityDefinitions>
...
</apiSource>
```

**Comment by kongchen** [comment]
That makes sense.

**Comment by kongchen** [comment]
Hi, plese check https://github.com/kongchen/swagger-maven-plugin#security-definitions to see how to define it.

It's not possible to read xml node's attribute in pom.xml for a maven plugin, so I did not follow the way you suggested.

Also, try 3.0.1-SNAPSHOT.

**Comment by who** [comment]
Thanks, this works!
