### ISSUE TITLE
[SpringMVC] Paths are not being rendered correctly when using multiple controllers.

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#140]
When the value of multiple method-level `@RequestMapping` are the same across different controllers, the paths are not being rendered correctly. 

I have observed that `@RequestMapping`s from controller A are being rendered as children of controller B's path because the `@RequestMapping` is the same for both methods.  Controller A and B have different class-level  `@RequestMapping` values.

**Comment by kongchen** [comment]
Thanks, another bug. 

3.0.1-SNAPSHOT should have it fixed.

**Comment by who** [comment]
Thanks for the fix.  It's working correctly now.
