### ISSUE TITLE
@ApiParam(required=true) parameters are rendered as not required

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#143]
`@ApiParam(required=true)` parameters are rendered as not required.

Example: This  [`required=true` parameter](https://github.com/kongchen/swagger-maven-example/blob/master/src/main/java/com/github/kongchen/swagger/sample/wordnik/resource/PetResource.java#L77) renders as  [`"required": false`](https://github.com/kongchen/swagger-maven-example/blob/master/generated/swagger-ui/swagger.json#L41).

**Comment by kongchen** [comment]
Please try 3.0.1-SNAPSHOT

**Comment by who** [comment]
Thanks, confirmed the fix in  3.0.1-SNAPSHOT
