### ISSUE TITLE
ApiImplicitParams are not rendered

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#146]
When I add `@ApiImplicitParam` annotation to an `@ApiOperation`, they are not rendered in the output by swagger-maven-plugin.

**Comment by who** [comment]
@kongchen I am working on a fix for this.

**Comment by kongchen** [comment]
Great! I was busying in some other affairs these days and today I'm available.
If you're working on this, I'll skip this issue and wait for your PR.
Thanks.

**Comment by who** [comment]
@kongchen 

This is my plan for the feature:

Create a factory that will convert `@ApiImplicitParam` to the correct Type (QueryParameter, BodyParameter, etc) and add it to the operation parameter list.

You can see my initial commit here: 
https://github.com/who/swagger-maven-plugin/blob/82b8ae9f5338f017dfc7d47d9b33917f4590972d/src/main/java/com/github/kongchen/swagger/docgen/reader/SpringMvcApiReader.java#L336-L413

With this commit, I have the following output: 

**Method**

```
    @ApiOperation(value="testingApiImplicitParams")
    @RequestMapping(
        value = "/testingApiImplicitParams", 
        method = RequestMethod.GET, 
        produces = "application/json")
    @ApiImplicitParams(value={
        
        @ApiImplicitParam(name="header-test-name", value="header-test-value", allowMultiple = true,
                required=true, dataType="string", paramType = "header", defaultValue = "header-test-defaultValue"),
        
        @ApiImplicitParam(name="path-test-name", value="path-test-value", allowMultiple = true,
                required=true, dataType="string", paramType = "path", defaultValue = "path-test-defaultValue"),
        
        @ApiImplicitParam(name="body-test-name", value="body-test-value",
                required=true, dataType="java.util.Map", paramType = "body"),
        
        @ApiImplicitParam(name="form-test-name", value="form-test-value", allowMultiple = true,
                required=true, dataType="string", paramType = "form", defaultValue = "form-test-defaultValue"),
    })
    public String testingApiImplicitParams() {
        return "testing";
    }
```

**Output spec**

```
{
  ...
  "paths" : {
    "/testing/testingApiImplicitParams" : {
      "get" : {
        "tags" : [ "example" ],
        "summary" : "testingApiImplicitParams",
        "description" : "",
        "operationId" : "testingApiImplicitParams",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "header-test-name",
          "in" : "header",
          "required" : true,
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "default" : "header-test-defaultValue"
        }, {
          "name" : "path-test-name",
          "in" : "path",
          "required" : true,
          "type" : "string",
          "default" : "path-test-defaultValue"
        }, {
          "in" : "body",
          "name" : "body-test-name",
          "required" : true
        }, {
          "name" : "form-test-name",
          "in" : "formData",
          "required" : true,
          "type" : "array",
          "items" : {
            "type" : "string"
          },
          "default" : "form-test-defaultValue"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "string"
            }
          }
        }
      }
    }
  },
  ...
}
```

**Comment by kongchen** [comment]
Great, and I agree with you only put the parser in `SpringMvcApiReader`, in jaxrs mode, @ApiImplicitParam will be ignored.

**Comment by who** [comment]
@kongchen Actually, `@ApiImplicitParams` are generic to both SpringMVC and JAX-RS, so I should probably put this logic in the abstract reader.

**Comment by kongchen** [comment]
Here's the comments from 'ApiImplicitParam':
>While {@link com.wordnik.swagger.annotations.ApiParam} is bound to a JAX-RS parameter,
 method or field, this allows you to manually define a parameter in a fine-tuned manner.
 This is the only way to define parameters when using Servlets or other non-JAX-RS
 environments.

I think `ApiImplicitParam` is not necessary when using JAX-RS.

**Comment by kongchen** [comment]
But I'm OK to put it in abstract reader

**Comment by kongchen** [comment]
I'd like to release 3.0.1 once this patch is OK.

**Comment by kongchen** [comment]
How's going on?

**Comment by who** [comment]
This patch needs a lot more work in order to be ready.  The factory logic doesn't handle all of the properties of the `@ApiImplicitParams` yet, so things like `defaultValue`, `required`, and `allowMultiple` aren't quite working well yet.

**Comment by kongchen** [comment]
Cool， keep your own pace.

**Comment by who** [comment]
@kongchen This is now complete.  I just pushed it to master, including unit tests.

https://github.com/kongchen/swagger-maven-plugin/commit/fdaf4342cb7b3f25d125b84b2558606f65615f50
