### ISSUE TITLE
[SpringMVC] Class-grouped query parameters are not parsed 

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#152]
When I group query parameters into a class, and then use them in a @RequestMapping method, they are not picked up by swagger-maven-plugin.

Here are some examples of the SpringMVC `@RequestMapping` configuration I'm talking about:

http://stackoverflow.com/a/16942352
http://stackoverflow.com/a/22441179
http://www.jpalace.org/document/92/binding-and-validation-of-handler-parameters-in-spring-mvc-controllers

Here's some sample code: 

**Controller**

```
package com.github.who.examples.swaggermavenplugin.controller;

import com.github.who.examples.swaggermavenplugin.model.QueryParamGroup;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import com.wordnik.swagger.annotations.*;
import java.util.HashMap;
import java.util.Map;


@RestController
@Api(value="Example of a query group")
public class TestingController {
    @ApiOperation(value="classOfRequestParams")
    @RequestMapping(value = "/classOfRequestParams", method = RequestMethod.GET, produces = "application/json")
    public Map<String, Object> testingQueryGroup(QueryParamGroup queryParamGroup) {
        Map<String, Object> map = new HashMap<String, Object>();
        map.put("stringParam1", queryParamGroup.getParam1());
        map.put("stringParam2", queryParamGroup.getParam2());
        map.put("intParam", queryParamGroup.getIntParam());
        return map;
    }
}
```

**QueryParamGroup class**

```
package com.github.who.examples.swaggermavenplugin.model;

import com.wordnik.swagger.annotations.ApiParam;
import org.springframework.web.bind.annotation.RequestParam;

public class QueryParamGroup {
    public QueryParamGroup() {
    }
    private String param1;
    private String param2;
    private Integer intParam;

    public Integer getIntParam() {
        return intParam;
    }

    public void setIntParam(Integer intParam) {
        this.intParam = intParam;
    }

    public String getParam1() {
        return param1;
    }

    public void setParam1(String param1) {
        this.param1 = param1;
    }

    public String getParam2() {
        return param2;
    }

    public void setParam2(String param2) {
        this.param2 = param2;
    }
}
```

After this controller and class are in place, here is how SpringMVC will handle it:

**Request**

```
GET /example/classOfRequestParams?param1=alpha&param2=bravo&intParam=5
```

**Response**

```
{
    param1: "alpha",
    intParam: 5,
    param2: "bravo"
}
```

**Comment by who** [comment]
@kongchen I have a fix for this, and I will prepare a PR.

**Comment by kongchen** [comment]
Thanks for the PR and the materials about SpringMvc.
I have a question here, in the reference http://stackoverflow.com/a/16942352 , it demonstrates `ModelAttribute` is not a must, and it seems we have no logic to cover this case, right?

**Comment by who** [comment]
Usually, `@ModelAttribute` is optional.  However, it is commonly used to as a marker to signal that the param is a bean of RequestParams.  I decided to make `@ModelAttribute` required for triggering our specific bean inspection logic. If we do not require it, we may be over-analyzing beans in RequestMappings.

**Comment by kongchen** [comment]
I see. So would you mind add some comments in README.md to explain this usage?
Thanks.

**Comment by who** [comment]
@kongchen Sure, I can do that

**Comment by watery** [comment]
@kongchen Hello, I'm not sure to understand whether this has been addressed or not, I see this is linked to [milestone 3.0.1](/kongchen/swagger-maven-plugin/milestone/8), but I'm using `3.1.7` and it doesn't seem to work.

From this controller code

```
@CrossOrigin(origins = "*", maxAge = 3600)
@RestController
@RequestMapping(path="/users", produces="application/json")
public class UserController {

	@Autowired
	private UserService userService;
	
	@Autowired
	private PlanningController planningController;
	
	@GetMapping(path="")
	public ApiResponse<List<User>> getUsers(@ModelAttribute UserFilter filter) {
		// ...
	}
	
	@GetMapping(path="/{userId}")
	public ApiResponse<User> getUser(@PathVariable String userId) {
		// ...
	}
	
	@GetMapping(path="/{userId}/plannings")
	public ApiResponse<List<Planning>> getUserPlannnings(@PathVariable String userId, PlanningFilter filter) {
		// ...
	}
	
	@InitBinder
	public void initBinder(WebDataBinder binder) {
		// ...
	}

}
```

mvn compile says

```
[INFO] picking up response class from method public api.ApiResponse app.api.users.UserController.getUserPlannnings(java.lang.String,app.api.plannings.PlanningFilter)
[INFO] picking up response class from method public api.ApiResponse app.api.users.UserController.getUser(java.lang.String)

```

There's no mention of `UserController.getUsers()`.

**Comment by tpischke-bedag** [comment]
Testing this, I see a number of limitations:
1. In the method signature, the DTO containing the request params must be annotated with @ModelAttribute or @ApiParam or it will be ignored.
2. Inside the DTO an @ApiParam annotation is required on each parameter
3. @ApiParam works only on a setter, not on a field, even if SpringMVC is configured to use field access. Thus code is forced to use unnecessary getters/setters just for this plugin.
4. Complex types annotated with @JsonDeserialize/@JsonSerialize appear to be ignored and do not appear in the generated spec.

Taken together, this makes it very difficult to use this feature (grouped request params).
