### ISSUE TITLE
dependencies containing @Path and @Api are not processed

### ISSUE THREAD

**Issue by jieryn** [kongchen/swagger-maven-plugin#169]
I have many common JAX-RS @Path in dependent jars, they are documented with wordnik annotations, @Api, etc. These dependent jars on the classpath are not found by swagger-m-p, and so the swagger.json is incomplete.

Please have this plugin scan the entire classpath for swagger annotations. Thanks!

**Comment by who** [comment]
@jieryn Have you added all of the containing packages to the`locations` section of your pom.xml ?

**Comment by jieryn** [comment]
My full configuration is:

```
  <build>
    <plugins>
      <plugin>
        <groupId>com.github.kongchen</groupId>
        <artifactId>swagger-maven-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <apiSources>
            <apiSource>
              <basePath>/ws/rs</basePath>
              <swaggerDirectory>${project.build.directory}/${project.build.finalName}</swaggerDirectory>
            </apiSource>
          </apiSources>
        </configuration>
        <executions>
          <execution>
            <phase>compile</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

**Comment by jieryn** [comment]
Ok, I had them at runtime scope, when I put them at compile scope they were found. I think the only problem with this is that I need to specify locations whereas previously it would appear to scan the entire source tree. It would be nice if swagger-m-p would look through all dependencies without having to specify a package name.

**Comment by kongchen** [comment]
Thanks for your advice, but I think specify the location is necessary.

**Comment by jieryn** [comment]
The examples you have in your own documentation don't specify it.. it's not required in the base case. It only seems to be required for classpath scanning, which is unfortunately quite inconsistent.

**Comment by kongchen** [comment]
Well, I'll update the document to mark the field as `required`, this is the only way for the plugin to scan apis.
