### ISSUE TITLE
generate goal configuration violates DRY

### ISSUE THREAD

**Issue by jieryn** [kongchen/swagger-maven-plugin#170]
I already have coded ```@javax.ws.rs.ApplicationPath("/api")``` on my ```javax.ws.rs.core.Application```, the generate goal should not require me to specify ```<apiSource><basePath>/api</basePath></apiSource>```.

**Comment by kongchen** [comment]
DRY is a good principle but not easy to follow in real world, as you seen in `@javax.ws.rs.ApplicationPath`'s doc:
>When published in a Servlet container, the value of the application path may be overridden using a servlet-mapping element in the web.xml

**Comment by jieryn** [comment]
Ok, I see that it is possible for it ot be overridden in some strange use cases, but why can't this be picked up as the default? Why make me do more work..?
