### ISSUE TITLE
model link is broken for composite model object

### ISSUE THREAD

**Issue by hongxingli** [kongchen/swagger-maven-plugin#171]
Example:

public class RegisterSpec {
    private Account account;
    private User user;
    ....
} 
public class Account {
    private String name;
    ....
} 

The link for account and user have extra #/definitions in both display and URL.

Thanks!
Hongxing

**Comment by kongchen** [comment]
Sorry, dude, I'm not sure what you mean, could you please describe this issue like #163 does?

**Comment by hongxingli** [comment]
Hi Yukai, thanks fort the quick response!

For about definition, if it's used as param, in html doc, for Account in RegisterSpec it will be generated as
                    <a href="#/definitions/#/definitions/Account">#/definitions/Account</a>
There are extra "#/definitions/#/" in both href and name itself.

sample code as
    @POST
    @Path("/register")
    @ApiOperation(value = "Register an account", notes = "Register a new account with default user", response = RegisterSpec.class)
    public void registerAccount(@Suspended final AsyncResponse asyncResponse,
            @ApiParam(value = "Account registration information", required = true) RegisterSpec regSpec);

**Comment by kongchen** [comment]
@hongxingli I still failed to reproduce your issue, don't know what I missed.

According to the test cases in this repo, as my understanding, the model [Pet](https://github.com/kongchen/swagger-maven-plugin/blob/master/src/test/java/com/wordnik/sample/model/Pet.java#L30) likes `RegisterSpec ` in your example, and `Category` likes your `Account`, and you can see, the generated html file looks good: https://github.com/kongchen/swagger-maven-plugin/blob/master/src/test/resources/sample.html#L1850

There's no extra `#/definitions`.

Does the case as same as your example?

**Comment by hongxingli** [comment]
Here is exactly what I see: 
http://htmlpreview.github.io/?https://raw.github.com/kongchen/swagger-maven-example/master/generated/document.html#/definitions/Pet

See this link, click on the category, it will show #definitions in the link

**Comment by kongchen** [comment]
I see.

The problem is caused by template file issue, I've update the template in https://github.com/kongchen/swagger-maven-example, it should be OK now.

Thanks for the finding.

**Comment by hongxingli** [comment]
Thanks!
