### ISSUE TITLE
SpringMavenDocumentSource can't use specFilter

### ISSUE THREAD

**Issue by piotrbazan** [kongchen/swagger-maven-plugin#173]
When adding specFilter to the SpringMavenDocumentSource (similar to the one in MavenDocumentSource):
``` java
    private ApiListing getDocFromSpringResource(SpringResource res, SwaggerConfig swaggerConfig) throws Exception {
        SpringMvcApiReader reader = new SpringMvcApiReader(apiSource, this.overriderConverter);
        ApiListing apiListing = reader.read(res, swaggerConfig);
        if (None.canEqual(apiListing)) return null;

        return specFilter.filter(apiListing, FilterFactory.filter(),
                Map$.MODULE$.<String, scala.collection.immutable.List<String>>empty(),
                Map$.MODULE$.<String, String>empty(),
                Map$.MODULE$.<String, scala.collection.immutable.List<String>>empty());
    }
```
the tests fail due to apiListing->models->car->subTypes constains native types:
(0)  = {java.lang.String@2117} "int"
(1)  = {java.lang.String@2119} "String"
(2)  = {java.lang.String@2121} "String"
(3)  = {java.lang.String@2123} "boolean"
(4)  = {java.lang.String@2125} "float"
(5)  = {java.lang.String@2127} "String"
(6)  = {java.lang.String@2129} "List"
(7)  = {java.lang.String@2131} "DateTime"

When tested MavenDocumentSource the Car model hast filtered subTypes.

Branch/tag: swagger-maven-plugin-2.3.4

**Comment by kongchen** [comment]
Hi @piotrbazan I'm not going to take time on 2.3.4 which follows Swagger Spec 1.2 any more, is it possible for you to switch to Swagger Spec 2.0 and use the version of 3.0.1 of this plugin?
