### ISSUE TITLE
Use new versions of swagger core dependencies

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#181]
On June 6th, swagger core released new versions of its core projects. As a part of the release, they repackaged their package names from com.wordnik.* into io.swagger.*.  We should switch dependencies to the new versions and perform and required refactoring of the swagger-maven-plugin codebase.

Here are the new dependencies:

```
        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jaxrs</artifactId>
            <version>1.5.0</version>
        </dependency>

        <dependency>
            <groupId>io.swagger</groupId>
            <artifactId>swagger-jersey-jaxrs</artifactId>
            <version>1.5.0</version>
        </dependency>
```

**Comment by who** [comment]
Update: @sudohippe, @hyeghiazaryan, and @who are working on this.

**Comment by who** [comment]
Hey @kongchen , we've been working on updating and refactoring swagger-maven-plugin to use the new version of swagger-core.  We are building on this fork: https://github.com/sudohippie/swagger-maven-plugin/tree/develop_core-refact 

Everything is ported over, and tests are passing. 

Would you agree with a PR ?

**Comment by sudohippie** [comment]
@who, @hyeghiazaryan, @kongchen - Created PR #184 with changes.

**Comment by who** [comment]
PR merged!  Thanks @sudohippie and @hyeghiazaryan

**Comment by kongchen** [comment]
Thank you all!

**Comment by mortias** [comment]
hi all, when would it be released?

**Comment by kongchen** [comment]
try 3.1.0
