### ISSUE TITLE
Add YAML output

### ISSUE THREAD

**Issue by webron** [kongchen/swagger-maven-plugin#182]
In Swagger 2.0, YAML has become a first-class citizen of the spec. As such, producers are expected to produce both JSON and YAML and consumers are expected to consume both.

**Comment by owainlewis** [comment]
+1

**Comment by typekpb** [comment]
+1

**Comment by mortias** [comment]
String fn = "C:\\PrivateWS\\applications\\rest\\target\\swagger-json\\swagger.json";
        String jsonString = FileUtils.readFileToString(new File(fn));

        ObjectMapper objectMapper = Json.create();
        Swagger swagger = objectMapper.readValue(jsonString, Swagger.class);
        Yaml.prettyPrint(swagger);

**Comment by mortias** [comment]
did a little effort :)
https://github.com/kongchen/swagger-maven-plugin/pull/242

**Comment by who** [comment]
Wow @mortias , thank you!

**Comment by who** [comment]
PR merged.

@kongchen, could you please push the latest to the snapshot repo?

**Comment by mortias** [comment]
you can close this issue

**Comment by who** [comment]
@webron Yaml support has been released with swagger-maven-plugin 3.1.1-RELEASE.

Thanks again @mortias for the contribution.
