### ISSUE TITLE
3.0.1-SNAPSHOT setup does not work with 3.1.0

### ISSUE THREAD

**Issue by ronsmits** [kongchen/swagger-maven-plugin#185]
Below is the configuration I use. When changing the plugin version to 3.0.1-SNAPSHOT it works. Running it with 3.1.0 brings only the information block.

    <plugin>
       <groupId>com.github.kongchen</groupId>
       <artifactId>swagger-maven-plugin</artifactId>
       <version>3.1.0</version>
       <configuration>
          <apiSources>
              <apiSource>
                  <springmvc>false</springmvc>
                   <locations>nl.salvesdevelopment.salvesgoals.rest</locations>
                  <schemes>http</schemes>
                  <host>ronsmits.org</host>
                  <basePath>/backend/api</basePath>
                  <info>
                      <title>Salves Goals and Measurements</title>
                     <version>v1</version>
                     <description>Rest server to users, goals and measurements</description>
                 </info>
                 <templatePath>${basedir}/templates/strapdown.html.hbs</templatePath>
                 <outputPath>${basedir}/generated/document.html</outputPath>
                 <swaggerDirectory>generated/swagger-ui</swaggerDirectory>
              </apiSource>
            </apiSources>
          </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by kongchen** [comment]
Which namespace of swagger are you using? if you're using `io.swagger`, you'd use `3.1.0`. If you're using `com.wordnik`, you'd choose `3.0.1` of this plugin.

**Comment by ronsmits** [comment]
Thank you, that solved that issue, the other issue I have now is with the authorization, I will open a seperate ticket for that
