### ISSUE TITLE
security.json seems not to be read

### ISSUE THREAD

**Issue by ronsmits** [kongchen/swagger-maven-plugin#186]
I have defined a security.json file like this:

    {
      "api_key": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    } 

Defined in the pom as:

    <securityDefinitions>
        <securityDefinition>
            <json>${basedir}/security.json</json>
        </securityDefinition>
    </securityDefinitions>

When running ````mvn compile```` it gives:
````
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.0:generate (default) on
 project backend: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to
 end-of-input
````

**Comment by kongchen** [comment]
I guess the issue is the json format, please check it carefully or use some tools like http://jsonformatter.curiousconcept.com/

**Comment by jodastephen** [comment]
Just to note for Google search results that this error is typically due to the json file not being found. In the pom.xml above, the `${basedir}` is not permitted as the json file is loaded by the Java resource system,`getClass().getResourceAsStream()`, not in the standard maven way.
