### ISSUE TITLE
3.1.1 -SNAPSHOT is not published to repositories

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#191]
@kongchen It looks like 3.1.1-SNAPSHOT isn't pushed to sonatype.  Could you please do that?

**Comment by kongchen** [comment]
Done!

2015-06-19 1:22 GMT+08:00 Andrew B <notifications@github.com>:

> @kongchen <https://github.com/kongchen> It looks like 3.1.1-SNAPSHOT
> isn't pushed to sonatype. Could you please do that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kongchen/swagger-maven-plugin/issues/191>.
>



-- 
Regards,
Kong

**Comment by who** [comment]
Thanks

**Comment by appienvanveen** [comment]
Any idea, when the 3.1.1 version will be release to the central maven repos?
