### ISSUE TITLE
Add @RequestBody and @RequestParam to whitelisted annotations for SpringMVC

### ISSUE THREAD

**Issue by tedleman** [kongchen/swagger-maven-plugin#192]
Hi guys,

Great job with moving this plugin to the 2.0 spec. Recently when testing, I found that parameters with Spring annotations @RequestParam and @RequestBody are not picked up, and shouldn't necessarily require @ApiParam annotations. This can be fixed by adding them to the "whitelist" in AbstractReader

**Comment by who** [comment]
@tedleman Can you think of any other Spring annotations to add to the whitelist ?

**Comment by tedleman** [comment]
There may also be some demand for using @PathVariable without @ApiParam, so that could probably go on the whitelist as well

**Comment by tedleman** [comment]
Updated https://github.com/kongchen/swagger-maven-plugin/pull/193

**Comment by kongchen** [comment]
Thank you guys, I just deploy the SNAPSHOT version
