### ISSUE TITLE
springmvc: @RequestMapping on the class level should be optional

### ISSUE THREAD

**Issue by adeyneka** [kongchen/swagger-maven-plugin#196]
It valid case for springvmc when @RequestMapping is specified only on method level.
Such cases are ignored now.
```java
@Api(value = "/pet")
public interface PetResource {

  @ApiOperation(value = "Find pet by ID")
  @RequestMapping(value = "/{petId}", method = RequestMethod.GET)
  Pet getPetById(@PathVariable("petId") Long petId);
}
```

**Comment by tedleman** [comment]
I made a PR to fix this: https://github.com/kongchen/swagger-maven-plugin/pull/201

But if you just put @RequestMapping(value="") at the class-level, it will work.

**Comment by who** [comment]
@adeyneka The PR from @tedleman is now in 3.1.1-SNAPSHOT.  

Please re-open this issue if you have continued trouble.
