### ISSUE TITLE
typesToSkip not recognized by plugin

### ISSUE THREAD

**Issue by marrufatzinio** [kongchen/swagger-maven-plugin#200]
TypesToSkip seems not being recognized by the plugin for some reason. When generating the documentation, I got the following error

`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.0.0:generate (default) on project content-transform-rest: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.0.0:generate for parameter apiSource: Cannot find setter, adder nor field in com.github.kongchen.swagger.docgen.mavenplugin.ApiSource for 'typesToSkip' -> [Help 1]
`

My pom configuration is the following

```xml
		<groupId>com.github.kongchen</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<apiSources>
						<apiSource>
						...	
					<templatePath>${basedir}/src/main/resources/static/handlebars/strapdown.html.hbs</templatePath>
							<outputPath>${basedir}/generated/document.html</outputPath>
							<swaggerDirectory>${basedir}/generated/swagger-ui</swaggerDirectory>
							<typesToSkip>
								<typeToSkip>com.foobar.skipper.SkipThisClassPlease</typeToSkip>
								<typeToSkip>com.foobar.skipper.AlsoSkipThisClassPlease</typeToSkip>
							</typesToSkip>
						</apiSource>
					</apiSources>
```

**Comment by who** [comment]
Hi @marrufatzinio , `typesToSkip` was added after swagger-maven-plugin 3.1.0 was released. You'll need to use the 3.1.1-SNAPSHOT for now.
