### ISSUE TITLE
How to set overriding models in swagger-maven-plugin 3.1.0

### ISSUE THREAD

**Issue by mkrzemien** [kongchen/swagger-maven-plugin#208]
How to set overriding models in swagger-maven-plugin 3.1.0?

It appears, that swagger-maven-plugin version 3.1.0 is missing the `overridingModels` option, that was present in version 2.3.

**Comment by tomasz314159** [comment]
Unfortunately, on https://github.com/swagger-api/swagger-core/wiki/overriding-models there is only an old description for version 1.3 instead of 1.5

**Comment by who** [comment]
Unless I am mistakedn, `overridingModels` is not compatible with Swagger spec 2.0+.

If you do wish to use swagger-maven-plugin 3.1.0, you may be able to get some of the behaviors of `overridingModels` by using [**model substitution**](https://github.com/kongchen/swagger-maven-plugin#model-substitution).
