### ISSUE TITLE
swagger-maven-plugin 3.1.0 version does not generate correct json

### ISSUE THREAD

**Issue by Toshuk3A** [kongchen/swagger-maven-plugin#209]
Steps:
1. Clone example https://github.com/kongchen/swagger-maven-example 
2. Change plugin version to **3.0.1**
3. Run mvn compile
4. Verify json file (**it is correct**)
5. Change plugin version to **3.1.0**
6. Run mvn compile
7. Verify json file (it has only INFO object)

**Comment by who** [comment]
You are correct; this is valid issue. The example project is not yet updated to work with 3.1.0.

**Comment by who** [comment]
@Toshuk3A I have updated the example project to be compatible with 3.1.0. 

You may find it here: https://github.com/swagger-maven-plugin/swagger-maven-example
