### ISSUE TITLE
The hidden attribute of @ApiParam doesn't work.

### ISSUE THREAD

**Issue by buri17** [kongchen/swagger-maven-plugin#210]
The swagger-maven-plugin ignores the hidden attribute of @ApiParam and generates swagger.json containing the api parameter.

**Comment by who** [comment]
@buri17 : which version of swagger-maven-plugin are you using ?

**Comment by richard-hulm** [comment]
+1 

I just checked the code out to try and get look this but it seems like the version of ApiParam the library is using doesn't match up with the latest one from Swagger (doesn't have the hidden field)

I couldn't find the dependency to update this, but if anyone's willing to point me in the right place or make this change would be appreciated!

**Comment by sbunciak** [comment]
I'm experiencing the same issue with version 3.1.0 of swagger-maven-plugin

**Comment by buri17** [comment]
I didn't notify @who 's comment. The version of swagger-maven-plugin is 3.1.0.

It depends on swagger-annotations 1.5.0. The hidden parameter was introduced in
swagger-annotations 1.5.1.

See https://github.com/swagger-api/swagger-core/releases/tag/v1.5.1.

**Comment by whisperwing** [comment]
+1. Could love to see it fixed.

**Comment by blakedy** [comment]
+1

**Comment by who** [comment]
@buri17 @blakedy @whisperwing @sbunciak @richard-hulm 

Hi all, I have just committed **swagger-core 1.5.3** support to **swagger-maven-plugin**.  `ApiParam(hidden=true)` should now work. 

@kongchen , would you please release a new snapshot to the snapshot repository ?

**Comment by who** [comment]
FYI, you will have to switch to  swagger-maven-plugin 3.1.1-SNAPSHOT to use `@ApiParam#hidden`.

**Comment by who** [comment]
@buri17 @blakedy @whisperwing @sbunciak @richard-hulm

Hi all, support for `@ApiParam#hidden` is now released to 3.1.1-SNAPSHOT. Please re-open this issue if you find any issues with it.
