### ISSUE TITLE
no api documentation is generated for locations

### ISSUE THREAD

**Issue by vhochstein** [kongchen/swagger-maven-plugin#213]
Hi, 
I wanted to try out swagger with my java8 spring 4.x maven project.
I ve used following dependencies:
```
<dependency>
            <groupId>io.swagger</groupId>
			<artifactId>swagger-core</artifactId>
			<version>1.5.3</version>
            <scope>compile</scope>
        </dependency>
<dependency>
```
and the following plugin
```
<plugin>
    <groupId>com.github.kongchen</groupId>
    <artifactId>swagger-maven-plugin</artifactId>
    <version>3.1.0</version>
    <configuration>
        <apiSources>
            <apiSource>
                <springmvc>true</springmvc>
                <locations>com.highstone.apps2mce.apps2Control</locations>
                <schemes>https</schemes>
                <host>apps.highstone.de</host>
                <basePath>/apps2mce/services</basePath>
```
....

Unfortuently, there no api documentation in my swagger.json, please find below.
So, I would guess plugin is not finding any controller files in specified locations.
Does anybody have an idea why that might happen?
As a test I ve specified a wrong location, same result.. So it seems there is no error generated in case location is wrong, for whatever reason.

Here s an example of one of my controllers

```
package com.highstone.apps2mce.apps2Control.rest.controller;

@Api(value="")
@Controller
public class AccountController extends BaseApps2MceController {
	static Logger logger = LoggerFactory.getLogger(AccountController.class);
	
	@Autowired
	private AccountService accountService;
	
	@Autowired
	private AccountServiceValidation accountServiceValidator;
	
	@RequestMapping(method=RequestMethod.GET)
	@ApiOperation(value = "List all pets")
    //@ApiModel(type = Pet.class, collection = true)
	public @ResponseBody List<AccountModel> listPets()
	{
		return new ArrayList<AccountModel>();
	}

```

{
  "swagger" : "2.0",
  "info" : {
    "description" : "This is a sample.",
    "version" : "15.4.1.6",
    "title" : "Box7 Service Documentation",
    "contact" : {
      "name" : "Volker Hochstein",
      "url" : "http://www.highstone.de",
      "email" : "volker.hochstein@highstone.de"
    }
  },
  "host" : "apps.highstone.de",
  "basePath" : "/apps2mce/services",
  "schemes" : [ "https" ]
}

**Comment by vhochstein** [comment]
just tried out the updated example https://github.com/swagger-maven-plugin/swagger-maven-example
I get a documentation for that project. 
Any idea how I may proceed with my project, which is not generating any service documenation?

**Comment by who** [comment]
@vhochstein the example project you linked is a JaxRS project, not a SpringMVC project, so it may not be applicable to your case.

For a SpringMVC example, check this out: https://github.com/who/swagger-maven-plugin-spring-mvc-example

**Comment by vhochstein** [comment]
Seems that 3.1.0 is broken upgrading to 3.1.1-SNAPSHOT fixed my issue
