### ISSUE TITLE
(Spring) No Api documentation generated if RequestMapping has no Value

### ISSUE THREAD

**Issue by richard-hulm** [kongchen/swagger-maven-plugin#218]
In Spring, the @RequestMapping annotation doesn't require a value

However, the plugin ignores my class if I just have @RequestMapping, while @RequestMapping(value = "") works fine

I suspect it's something to do with this line?

https://github.com/kongchen/swagger-maven-plugin/blob/ea49dbc8ff8fd9884f79c2ab144585d315168b04/src/main/java/com/github/kongchen/swagger/docgen/reader/SpringMvcApiReader.java#L377

For now, I've just amended the requestmapping to have value= ""

**Comment by GeekJJ** [comment]
Agree, and I think this should be fixed, as @RequestMapping(value="") is a little strange.

**Comment by chrisschauer** [comment]
+1

Same problem with a multi-action controller without @RequestMapping Annotation on class level. The Controller looks like: 

```
@Api(value = "/", description = "Description")
@RestController
public class MyController implements MyInterface{
..
    @RequestMapping(value = CONST_FROM_INTERFACE,
            method = RequestMethod.GET)
 public String myExampleMethod(){
  ....
 }
}
```
