### ISSUE TITLE
Circular referencing not working

### ISSUE THREAD

**Issue by sunandabbytes** [kongchen/swagger-maven-plugin#224]
I using swagger-maven-plugin to generate swagger.json and swagger2markup-maven-plugin to process json and generate asciidoc. 

During maven build is failing due to the error-- Execution output-asciidoc of goal com.redowlanalytics:swagger2markup-maven-plugin:0.8.0:process-swagger failed: property must not be null!  
Its failing while processing User definition.

Json generated has user and address definitions as
User definition
        "addresses" : {
          "type" : "array"
        },

Address definition
        "users" : {
          "type" : "array",
          "items" : {
            "$ref" : "#/definitions/address"
          }
        }

But if I generate swagger.json using springfox and use it here it is working. But I want swagger-maven-plugin to generate json, so that I get pdf generated during build using asciidoctorj-pdf.
pom.xml

		<plugin>
				<groupId>com.github.kongchen</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<apiSources>
						<apiSource>
							<springmvc>true</springmvc>
							<locations>com.app.controller.impl</locations>
							<schemes>http,https</schemes>
							<host>http://localhost:8081/myapp</host>
							<basePath>/*</basePath>
							<info>
								<title>rest services</title>
								<version>v1</version>
								<description>Documentation</description>
								<contact>
									<email>myid@gmail.com</email>
									<name>Name</name>
								</contact>
							</info>
							<swaggerDirectory>${generated.swagger.directory}</swaggerDirectory>
						</apiSource>
					</apiSources>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			
			<plugin>
                <groupId>com.redowlanalytics</groupId>
                <artifactId>swagger2markup-maven-plugin</artifactId>
                <version>0.8.0</version>
                <configuration>
                    <inputDir>${generated.swagger.directory}</inputDir>
                    <outputDir>${generated.asciidoc.directory}</outputDir>
                    <markupLanguage>asciidoc</markupLanguage>
                </configuration>
                <executions>
					<execution>
						<id>output-asciidoc</id>
						<phase>package</phase>
						<goals>
							<goal>process-swagger</goal>
						</goals>
						<configuration>
							<inputDirectory>${generated.swagger.directory}</inputDirectory>
							<outputDirectory>${generated.asciidoc.directory}</outputDirectory>
							<markupLanguage>asciidoc</markupLanguage>
						</configuration>
					</execution>
				</executions>
            </plugin>

Please help me. Thanks in advance.

**Comment by wfuertes** [comment]
I would like say that I have the solution, instead of to say I'm with the same problem. So I will try to find a possible solution for that until the issue to fixed in future releases.

**Comment by wfuertes** [comment]
follow my context, include response class, end-point and js where the code brokers, because of a undefined property $ref.

Related: kongchen/swagger-maven-plugin#224
```
public class NodeTree {
	
    private Long id;
    private String name;
    private List<NodeTree> children;
	
	// GETTERS AND SETTERS
}
```

My documentated REST end-point.

```
@POST
@Path("/{treeId}/nodes")
@Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@ApiOperation(value = "Create node tree.")
@ApiImplicitParams(value = {
	@ApiImplicitParam(name = "nodeTree", value = "", required = true, dataType = "NodeTree",
					  paramType = "data")})
@ApiResponses(value = { @ApiResponse(code = 200, message = "Succees", response = NodeTree.class)})
public Response createNodeTree(@ApiParam(value = "Tree id", required = true) @PathParam("treeId") Long treeId, NodeTree nodeTree) {

	// IMPLEMENTATION OMITED 
}
```

So the swagger-maven-plugin is generating the follow swagger.json:

```
"NodeTree" : {
  "type" : "object",
  "required" : [ "name" ],
  "properties" : {
	"id" : {
	  "type" : "integer",
	  "format" : "int64"
	},
	"name" : {
	  "type" : "string"
	},
	"children" : {
	  "type" : "array"
	  /* Here missing the follow part: 
		  "items" : {
			"$ref" : "#/definitions/NodeTree"
		  }
	  */
	}
  }
}
```

Because this the "swagger-client.js" is breaking in the follow function:

----------------
```
Resolver.prototype.resolveTo = function (property, objs) {
  
  // it is breaking here, because we don't have 
  // $ref in the property to the type = array.
  var ref = property.$ref;
  
  if(ref) {
    if(ref.indexOf('http') === 0) {
      if(Array.isArray(objs[ref])) {
        objs[ref].push({obj: property, resolveAs: '$ref'});
      }
      else {
        objs[ref] = [{obj: property, resolveAs: '$ref'}];
      }
    }
  }
  else if(property.type === 'array') {
    var items = property.items;
    this.resolveTo(items, objs);
  }
}; 
----------------
```

I hope this can be useful in order to solve the problem.
Regards.
Willian.

**Comment by sunandabbytes** [comment]
Using 3.1.1-SNAPSHOT of swagger-maven-plugin solve the problem.

Thanks,
Sunanda
