### ISSUE TITLE
Interpret @NotNull as required.

### ISSUE THREAD

**Issue by mhaefele** [kongchen/swagger-maven-plugin#229]
SpringMVC has a "required" field on parameter annotations (like @RequestParam)
This correctly added to the generated Swagger json by the plugin.

Doing some minor research, it seems like a reasonable solution for JAX-RS to have the same behavior is to add a @NotNull (JSR-303) annotation to the parameter.

Wondering if it's feasible to have the plugin interpret that @NotNull annotation in the same way it interprets "required" in SpringMVC?

**Comment by who** [comment]
@mhaefele 

That's definitely possible, and we gladly accept PRs if you are feeling ambitious :)

For a workaround, swagger-maven-pluigin currently reads Spring's `required` attribute of `@RequestParam` annotation.

**Comment by oburgosm** [comment]
What is the state of this issue?

I've could test that this feature is implemented in current version (3.1.5) although I also have @RequestParam annotation. But i think that not always @NotNull means that parameter is required, for example, if there is a defaultValue.

**Comment by mhaefele** [comment]
Using the example maven config, it looks like this is adding @NonNull fields to the required list in the swagger json.
From my point of view, this is resolved.


@oburgosm  I'd curious what validators do in that case.  My hunch would be a field marked NotNull with a DefaultValue would actually reject it if missing and never use the default value.
