### ISSUE TITLE
Cannot add non-string example values in model properties

### ISSUE THREAD

**Issue by MrCastor** [kongchen/swagger-maven-plugin#233]
@ApiModelProperty currently has an "example" attribute which is correctly serialized as an example field in the output json model. However there is currently no way to deal with non-string values.

    Class ExampleTest {
       @ApiModelProperty (example = "1")
       Integer value;
       ...
    }

will be serialized as: 

    "ExampleTest" : {
        "type" : "object",
        "properties" : {
        "value" : {
           "type" : "integer",
            "format" : "int32",
            "example" : "1"      // Should be "example" : 1
          }
    }

As a result clients such as swagger-ui might use this value for filling test requests, which will fail server side because value does not match property type.

In order to fix this we implemented a small extension of the plugin (based on 3.1.1-SNAPSHOT), by adding a boolean option "serializeExampleAsRawJsonValue".  

If set, example in @ApiModelProperty should be expressed as a raw json value and will be serialized as such. The example above will lead to the expected integer value.  If "example" is really a string, ApiModelProperty example attribute value should be written as "\"abc\"" (instead of "abc"). The option defaults to false if omitted, which preserve backward compatibility.

Implementation actually relies on very few lines of code. Roughly, the idea  is to use a jackson mix-in class and a @JsonRawValue annotation to modify slightly the serialization of the swagger Property class.

Do you see any other way to fulfill this requirement ? If not, are you interested in a pull request for this feature ?

Thx

**Comment by who** [comment]
@MrCastor Yes, PRs are always welcome, and your approach sounds reasonable. There are some integration tests (for both JaxRS mode and SpringMVC mode) that should also be updated along with the PR.

**Comment by MrCastor** [comment]
PR sent. The final name of the option is `jsonExampleValues`.
Thx.

**Comment by who** [comment]
@MrCastor Thanks for contributing! I've merged https://github.com/kongchen/swagger-maven-plugin/pull/237

We will probably want to revisit this solution when swagger-core adresses https://github.com/swagger-api/swagger-core/issues/1318.
