### ISSUE TITLE
Unable to generate spec

### ISSUE THREAD

**Issue by jackOfAiiTrades** [kongchen/swagger-maven-plugin#241]
Sorry, this is probably not the right place to be asking this.  I tried searching for related stackexchange threads, asked in #swagger, but nobody seems to have this issue so I must be doing something exceptionally stupid.

Basically, I've followed the sample, set up the plugin configurations, added the annotations to the relevant classes, and when i clean compile package the project, no swagger files are created at all.

Can anyone help?

class annotations:
@Api(value = "/path", description = "Operations about ____")
@Produces({"application/json"})			

method annotations:
@GET
@Path("RetrieveInfo")
@Produces(MediaType.APPLICATION_JSON)
@ApiOperation(value = "Retrieve Info", 
    notes = "Returns info will simulate API error conditions", 
    response = Map.class)
			
			
			
pom entry (removed opening < on tags because full tag was being removed by forum):
			plugin>
            	groupId>com.github.kongchen</groupId>
            	artifactId>swagger-maven-plugin</artifactId>
            	version>3.1.0</version>
            	configuration>
                	apiSources>
                 	   apiSource>
                        	springmvc>false</springmvc>
        					basePath>/api</basePath>
        					supportSpringMvc>false</supportSpringMvc>
                        	locations>package.ClassName</locations>
                        	host>redacted</host>
                        	schemes>http</schemes>
                        	info>
                        		title>API Project</title>
                        		description>This provides the gateway for all externally available requests</description>
                        		version>0.1</version>
                        	/info>
                        	outputPath>${basedir}/generated/document.html</outputPath>
                            swaggerDirectory>${basedir}/generated/swagger-ui</swaggerDirectory>
                    	/apiSource>
                	/apiSources>
            	/configuration>
  				executions>
    				execution>
    				  	phase>compile</phase>
        				goals>
          					goal>generate</goal>
        				/goals>
    				/execution>
  				/executions>
        	/plugin>

**Comment by mortias** [comment]
Location should be a package path without the classname itself?

**Comment by jackOfAiiTrades** [comment]
TY mortias.

Yeah I wasn't sure about that, so I've tried it both ways, and neither work.

I've also tried a variety of outputPaths and swaggerDirectories, including "C:\Folder\Swagger", and generated/swagger-ui (same as posted but without the ${basedir}

FWIW - When I run the compile, I don't see anything in the output text mentioning swagger at all.

**Comment by mortias** [comment]
can i see / download your code somewhere?

**Comment by jackOfAiiTrades** [comment]
not in its current form, id have to remove the actual code, and refactor the methods, but that's not problem.  what do you need to see, just the pom and a class in the locations that has the annotations?

**Comment by mortias** [comment]
your basepath is /api but you don't have your class set in the package "api" ?

**Comment by jackOfAiiTrades** [comment]
no, will that cause issues?

packages is com.something.something.services, and i have several classes
with various paths/resources as part of that package.

**Comment by mortias** [comment]
ah true, no that's not related,.. getting tired on a friday evening :)
is your locations then set on that path? <locations>com.something.something</..

**Comment by jackOfAiiTrades** [comment]
i've tried with locations set to "com.something.something.services" and
"com.something.something.services.Service1"

**Comment by raptortech-js** [comment]
What happens if you include a templatePath (even if you don't actually want HTML output)?

**Comment by jackOfAiiTrades** [comment]
hey Jackie, ty for response.

I've tried including template path (no luck) but without an actual
template... so probably not a full test of it.

I'm not fully sure how to create a template, I see this example:
https://github.com/kongchen/swagger-maven-example/blob/master/templates/markdown.hbs

Would it be enough to copy that into directory?

**Comment by raptortech-js** [comment]
I think you'll need to copy all the files in the sample /templates/ directory into the /templates directory in your project

**Comment by raptortech-js** [comment]
If you don't give a template path at all, you'll run into this code:
```
				if (apiSource.getTemplatePath()!=null) {
					documentSource.toDocuments();
				}
```
in https://github.com/kongchen/swagger-maven-plugin/blob/07966276ad161be80a013600706c64c093622f5b/src/main/java/com/github/kongchen/swagger/docgen/mavenplugin/ApiDocumentMojo.java

**Comment by who** [comment]
@jackOfAiiTrades What is the full namespace of the `@Api` annotation class that you are using?

**Comment by jackOfAiiTrades** [comment]
com.wordnik.swagger.annotations.Api;

**Comment by who** [comment]
@jackOfAiiTrades 

Ok, that is the problem.

With the release of swagger-maven-plugin 3.1.0, we included support for the new (at the time) version of swagger-core, which re-factorted/re-packaged it's namespaces from com.wordnik.* to io.swagger.*.

You will have to switch over your namespaces and try again.

Here's a snippet in the documentation regarding this: https://github.com/kongchen/swagger-maven-plugin#upgrading-from-301-to-310

Here's a commit from when I upgraded to io.swagger.* compatible namespces in the example project: https://github.com/swagger-maven-plugin/swagger-maven-example/commit/3d6bfa06d638d0855edc04816d4e35bff4a5e771#diff-600376dffeb79835ede4a0b285078036

**Comment by who** [comment]
@jackOfAiiTrades 

Also, here's someone else who had the exact same issue: 
https://github.com/kongchen/swagger-maven-plugin/issues/189

**Comment by jackOfAiiTrades** [comment]
Ty Andrew.

I've updated now, based on your comment, but still nothing being generated.

Not an empty file, no file at all.  I don't see any output related to
swagger in the Maven compile output.

Is there any way to tell if anything is being attempted at all via Swagger?

**Comment by raptortech-js** [comment]
If it properly outputs files, it should look roughly like this:

[INFO] --- swagger-maven-plugin:3.1.1-SNAPSHOT:generate (execution1) @
aws.testing.jersey6 ---

[INFO] Reflections took 51 ms to scan 1 urls, producing 2 keys and 5 values

[INFO] Looking for path/query/header/form/cookie params in class
java.lang.String

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in int

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in class
java.lang.String

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in int

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in class
java.lang.String

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in int

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in class
java.lang.String

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Looking for path/query/header/form/cookie params in int

[INFO] trying extension
com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@446626a7

[INFO] Writing doc to
/Users/jackie/Documents/workspace/RestfulWebservice2/target/docs/document.html...

[INFO] Done!


Do you see any of this at all? If you don't see even the first line, then
you probably didn't specify the swagger:generate goal

**Comment by jackOfAiiTrades** [comment]
Yeah I dont see any of that.

I have

<configuration>
....
</configuration>
  <executions>
    <execution>
      <phase>compile</phase>
        <goals>
          <goal>generate</goal>
        </goals>
    </execution>
  </executions>

**Comment by raptortech-js** [comment]
And when you compile, are you just doing `mvn compile`? If so, what `groupId`, `artifactId`, and `version` are you using for the plugin?

**Comment by who** [comment]
@jackOfAiiTrades 

Would it be possible for you to create a gist or pastebin of `mvn clean compile -X` ?

**Comment by jackOfAiiTrades** [comment]
I would prefer not to for security reasons.

Have I missed any important steps?
Add dependency to pom.xml
Add plugin to pom.xml
Add annotations to at least 1 class.

**Comment by raptortech-js** [comment]
You shouldn't even need to add swagger-maven-plugin as a dependency, just as a plugin. If I comment out the entire `<configuration>...</configuration>` section of the plugin, I get an error: `Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.1-SNAPSHOT:generate (execution1) on project aws.testing.jersey6: You must configure at least one apiSources element -> [Help 1`. What do you get?

**Comment by jackOfAiiTrades** [comment]
Yep, just mvn compile.

<groupId>com.github.kongchen</groupId>
            <artifactId>swagger-maven-plugin</artifactId>
            <version>3.1.0</version>

**Comment by jackOfAiiTrades** [comment]
With no configuration section:

[INFO]
------------------------------------------------------------------------
[INFO] Building proxy 0.0.1-SNAPSHOT
[INFO]
------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ proxy ---
[INFO] Deleting .....\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ proxy
---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Copying 3 resources to config
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ proxy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 23 source files to....\target\classes
[INFO]
------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO]
------------------------------------------------------------------------

**Comment by raptortech-js** [comment]
Hmm. That's really weird. I'm not sure but what if you try `mvn compile swagger:generate`? That *should* force it to run the generate goal.

**Comment by jackOfAiiTrades** [comment]
That's it!  I'm the proud owner of a brand-spankin' new swagger.json.

Not sure why

  <executions>
    <execution>
      <phase>compile</phase>
        <goals>
          <goal>generate</goal>
        </goals>
    </execution>
  </executions>
wasn't triggering it, clean compile swagger:generate worked.

Really appreciate all the help Jackie, Andrew, and co., this was driving me
batty.

**Comment by raptortech-js** [comment]
Congrats! Oh is there any chance you were working in Eclipse with m2e? My m2e installation doesn't seem to like this execution, for no apparent reason. Also, you should probably close the issue.

**Comment by jackOfAiiTrades** [comment]
Yep, m2e.  Closing now.
