### ISSUE TITLE
Please release 3.1.1-SNAPSHOT as 3.1.1-RELEASE

### ISSUE THREAD

**Issue by who** [kongchen/swagger-maven-plugin#244]
@kongchen We should release 3.1.1-SNAPSHOT as 3.1.1-RELEASE and bump the snapshot version to 3.1.1-SNAPSHOT.

What do you think ?

**Comment by grunci** [comment]
Good idea. I wanted to ask when will be the next release. :)

**Comment by who** [comment]
@kongchen I've just committed some massive integration test updates, and also committed support for swagger-core 1.5.4 (the latest one as of this writing).

I think we should put a plan together to get master this released, as it has been stable for awhile, and has many, many improvements.

**Comment by mortias** [comment]
+1, after my latest pull request ;)

**Comment by kongchen** [comment]
Sorry guys, I'll release it soon

2015-11-05 3:36 GMT+08:00 Mortier Andries <notifications@github.com>:

> +1, after my latest pull request ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kongchen/swagger-maven-plugin/issues/244#issuecomment-153840807>
> .
>



-- 
Regards,
Kong

**Comment by mortias** [comment]
super, could you do it "asap" so I can take it up in our current sprint planning ;)

**Comment by who** [comment]
@kongchen 

I see that you've tagged the release - thanks!

It appears that 3.1.1 is not in the mvn repos yet: http://search.maven.org/#search%7Cga%7C1%7Cswagger-maven-plugin'

Which repos has the new version been propagated to?

**Comment by kongchen** [comment]
it should be there now.

2015-11-10 0:52 GMT+08:00 Andrew B <notifications@github.com>:

> @kongchen <https://github.com/kongchen>
>
> I see that you've tagged the release - thanks!
>
> It appears that 3.1.1 is not in the mvn repos yet:
> http://search.maven.org/#search%7Cga%7C1%7Cswagger-maven-plugin'
>
> Which repos has the new version been propagated to?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kongchen/swagger-maven-plugin/issues/244#issuecomment-155121061>
> .
>



-- 
Regards,
Kong

**Comment by who** [comment]
Thanks @kongchen
