### ISSUE TITLE
@RequestBody parameter generated with the name 'body'

### ISSUE THREAD

**Issue by itayavra** [kongchen/swagger-maven-plugin#257]
Hey,
I'm trying to generate a python REST client from my java sever code using the swagger.json created with swagger-maven-plugin-3.1.0.
The resulting description of the following method contains a parameter named 'body' instead of 'actionDTO'.

The java method:
@ApiOperation(value = "Create action", nickname = "createAction")
@RequestMapping(value = "/action", method = RequestMethod.POST)
public @ResponseBody
UUID create(@RequestBody ActionDTO actionDTO) throws PublicAlreadyExistsException {...}

In addition, this is not the only place it happens (everywhere in the code there a POST/PUT/DELETE request with @RequestBody parameter), resulting in many generated 'body' classes ('body1', 'body2', etc).
Is there a way to work around this?

Thanks,
Itay

**Comment by who** [comment]
@itayavra I believe this has been fixed recently. Please change your swagger-maven-plugin version to 3.1.2.
