### ISSUE TITLE
When is the next release coming out?

### ISSUE THREAD

**Issue by ankurvsoni** [kongchen/swagger-maven-plugin#297]
@kongchen - When is the next release coming out?

I am specifically interested in features like: typesToSkip, modelConverters.

**Comment by jeremyunruh** [comment]
+1 @kongchen at the very least could you deploy a new snapshot?  Last snapshot looks like it was 3.0 :(

**Comment by who** [comment]
+1 

@kongchen 

Please release the current 3.1.3-SNAPSHOT to the snapshot repository, and then tag the version for 3.1.3-RELEASE, and then bump the current working version in master to 3.1.4-SNAPSHOT.

I do have commit permissions, but I do not have permissions to release. If you like, I could take responsibility for releasing as well, but I will need repo credentials from you.

**Comment by kongchen** [comment]
Hi guys, sorry for the slow response. I've just released 3.1.3

2016-02-17 1:51 GMT+08:00 Andrew B <notifications@github.com>:

> +1
>
> @kongchen <https://github.com/kongchen>
>
> Please release the current 3.1.3-SNAPSHOT to the snapshot repository, and
> then tag the version for 3.1.3-RELEASE, and then bump the current working
> version in master to 3.1.4-SNAPSHOT.
>
> I do have commit permissions, but I do not have permissions to release. If
> you like, I could take responsibility for releasing as well, but I will
> need repo credentials from you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kongchen/swagger-maven-plugin/issues/297#issuecomment-184798462>
> .
>



-- 
Regards,
Kong

**Comment by rakk** [comment]
Hi guys,

I just checked [mvnrepository.com/artifact/com.github.kongchen/swagger-maven-plugin](http://mvnrepository.com/artifact/com.github.kongchen/swagger-maven-plugin) the release is not visible yet.
Do you know how long it will take to see the release in maven central repository?
