### ISSUE TITLE
REST services and API docs can't be located at different URLs

### ISSUE THREAD

**Issue by vbauer** [kongchen/swagger-maven-plugin#30]
I have the following plugins configuration:

``` xml
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <configuration>
                    <webResources>
                        <resource>
                            <directory>${build.directory}/restapi</directory>
                            <targetPath>restapi</targetPath>
                        </resource>
                    </webResources>
                </configuration>
            </plugin>

            <!-- Swagger plugin -->
            <plugin>

                <groupId>com.github.kongchen</groupId>
                <artifactId>swagger-maven-plugin</artifactId>
                <version>${maven.swagger.plugin.version}</version>
                <configuration>
                    <apiSources>
                        <apiSource>
                            <locations>com.simba.rest</locations>
                            <apiVersion>v1</apiVersion>
                            <withFormatSuffix>false</withFormatSuffix>
                            <useOutputFlatStructure>false</useOutputFlatStructure>
                            <swaggerDirectory>${build.directory}/restapi/doc</swaggerDirectory>
                            <basePath>http://localhost:8080/rest</basePath>
                            <outputPath>${build.directory}/restapi/doc/rest.html</outputPath>
                            <outputTemplate>
                                https://raw.github.com/kongchen/api-doc-template/master/v1.1/html.mustache
                            </outputTemplate>
                        </apiSource>
                    </apiSources>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

        </plugins>
```

As you see, my REST API located at "http://localhost:8080/rest" (basePath).
Generated API docs with swagger-ui files are located at "http://localhost:8080/restapi".

When I fetch service.json in swagger-ui, it looks like the following JSON document:

``` json
{
  "apiVersion" : "v1",
  "swaggerVersion" : "1.1",
  "basePath" : "http://localhost:8080/rest",
  "apis" : [ {
    "path" : "/scripts.{format}",
    "description" : "Scripts"
  }, {
    "path" : "/files.{format}",
    "description" : "Operations with resource files"
  }, {
    "path" : "/directories.{format}",
    "description" : "Operations with resource directories"
  } ]
}
```

Swagger-UI uses "basePath" ("http://localhost:8080/rest") to retrieve other REST services ("scripts", "directories", etc), but I haven't got API docs there. They are located at "/restapi/doc".

I investigated differences between generated files (swagger-maven-plugin vs swagger-jersey-jaxrs) and found the following moment: swagger-jersey-jaxrs doesn't configure "basePath" for root document ("service.json"), only for children.

I've tried to remove basePath from service.json (modified plugin sources) but it didn't help. Swagger-ui wants to fetch children docs using incorrect path, ex "http://localhost:8080/restapi/doc/service.json/directories.json".

Have you got any idea?

**Comment by xdraculax** [comment]
I think you may use two diferente configurations:

First, the adderess of service API (with Jersey, for example):
<basePath>http://localhost:8080/RESTService/api</basePath>

Second, use the the base path for the .json|.xml files:
<swaggerUIDocBasePath>http://localhost:8080/RESTService/api-doc</swaggerUIDocBasePath>

With these configurations, the plugin will put the base path for root json (service.json) with "api-doc", but for children json's the path will continue only "..../api".

This worked for me.
