### ISSUE TITLE
How to discard swagger annotations during run time

### ISSUE THREAD

**Issue by sunandabbytes** [kongchen/swagger-maven-plugin#303]
I am using swagger-maven-plugin and generating swagger.json during build. I wanted this json during build so that I can play around with json later.

But I dont need all swagger annotations after the maven build after generating json. During runtime I dont need annotation to be there. How can I ignore or change retention policy of an annotation to ignore annotation during runtime.

**Comment by IgorGursky** [comment]
I would suggest putting <**scope**>provided</**scope**> for annotations dependency. This way they will be used during compilation and not put as a libraty to the target Maven artifact.

Please comment if it worked!

**Comment by sunandabbytes** [comment]
Yes it worked. Now I don't find any dependencies swagger in built war. 

Thanks
