### ISSUE TITLE
Documentation issue - scheme configuration

### ISSUE THREAD

**Issue by dgoldfarble** [kongchen/swagger-maven-plugin#311]
In https://github.com/kongchen/swagger-maven-plugin#configuration-for-apisource:
```
The transfer protocol of the API. Values MUST be from the list: "http", "https", "ws", "wss". Each value must be located inside <scheme> tag
```
and in the sample pom:
```
<schemes>
    <scheme>http</scheme>
    <scheme>https</scheme>
</schemes>
```
But when I modify the sample (which uses \<schemes\>http,https\</schemes\>), I get:
```
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.1:generate (default) on project swagger-maven-example: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.1:generate for parameter apiSource: Basic element 'schemes' must not contain child elements -> [Help 1]
```

**Comment by who** [comment]
Documentation has been updated.

https://github.com/kongchen/swagger-maven-plugin/commit/0a0535dfcbfe3765e0dced8a4d77d4bb076f578f

**Comment by dgoldfarble** [comment]
Sorry, I wasn't clear. It seems that the
```
<schemes>
    <scheme>http</scheme>
    <scheme>https</scheme>
</schemes>
```
syntax is not valid (`Basic element 'schemes' must not contain child elements`). The sample uses 
`<schemes>http,https</schemes>` syntax.

**Comment by who** [comment]
@dgoldfarble 

Which version are you using? The documentation reflects the latest master, which is not yet released.

**Comment by dgoldfarble** [comment]
3.1.0

**Comment by who** [comment]
Ok, then you should be using this format: 
<schemes>http,https</schemes>

**Comment by nissimpradhan** [comment]
Hi, 
Is there somewhere i can view the documentation(format of API source) for different versions of the plugin? To avoid the problem @dgoldfarble had.

Thanks

**Comment by who** [comment]
@nissimpradhan Yes, browse the repository at the commit of the last release:

https://github.com/kongchen/swagger-maven-plugin/tree/22dab275f31653f4213aefedbad721de40ae8ecb
