### ISSUE TITLE
swagger.json wrong encoding

### ISSUE THREAD

**Issue by donsenior** [kongchen/swagger-maven-plugin#314]
Generated swagger.json content is written with platform default encoding instead of project encoding (in this case are different : project is UTF-8 and platform has ISO-8859-1).

Static document, however, is correctly written with project encoding.

[files.zip](https://github.com/kongchen/swagger-maven-plugin/files/209078/files.zip)

**Comment by proshin-roman** [comment]
I have the same problem. My project defines some set of special symbols that are forbidden for usage. I found that generated file has correct encoding (UTF-8), but these special symbols are incorrect! I guess plugin really uses some platform encoding during the processing.
