### ISSUE TITLE
Add support for externalDocs in apiSource

### ISSUE THREAD

**Issue by nissimpradhan** [kongchen/swagger-maven-plugin#325]
I was checking the [petstore example](http://petstore.swagger.io/) on swagger ui. If you look at the end of [swagger.json](http://petstore.swagger.io/v2/swagger.json) then there's a field called external docs which is the 
"Find out more about Swagger
http://swagger.io" on the swagger-ui
It's called externalDocs, it would be awesome if you could add support for it in apiSource :)

**Comment by JbaByteletics** [comment]
This is funny, it is referenced in the template, but still not implemented in the code. :-(
