### ISSUE TITLE
location elements inside locations tag are not working

### ISSUE THREAD

**Issue by matteosilv** [kongchen/swagger-maven-plugin#328]
We are obtaining the following error with the 3.1.3 plugin version

[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.3:generate (default) on project web-base: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.3:generate for parameter apiSource: Basic element 'locations' must not contain child elements -> [Help 1]

**Comment by AlexElin** [comment]
@matteosilv 

The documentation reflects the latest master, which is not yet released.
For version 3.1.3 you should specify locations as <locations>location1;location2</locations>

**Comment by matteosilv** [comment]
thanks!

2016-05-13 15:42 GMT+02:00 AlexElin <notifications@github.com>:

**Comment by watery** [comment]
@AlexElin Hi, I'm seeing this on `3.1.7`: can a note be added to the README.md? That would make it easier for newbies.

**Comment by princejha95** [comment]
I am facing the same issue in version 3.1.7 even when i am doing this:
<locations>
<location>location1</location>
<location>location2</location>
<location>location3</location>
</locations>

But only location1 is picked up.

**Comment by princejha95** [comment]
Any updates anyone for the above issue ?

**Comment by pablo53** [comment]
Why is this ticket closed? The issue is still present.

**Comment by jorfernandez** [comment]
> Why is this ticket closed? The issue is still present.

Aggree with @pablo53! I'm, using version 3.1.8 and still getting this error.

Edit: I have found the fix for this error. Let me attach the[ link to the solution](https://github.com/kongchen/swagger-maven-plugin/issues/688#issuecomment-446529916).
