### ISSUE TITLE
Cannot find 'swaggerFileName' during generate

### ISSUE THREAD

**Issue by danjo830** [kongchen/swagger-maven-plugin#332]
I'm running version 3.1.3 of swagger-maven-plugin and I'm trying to set the filename using the swaggerFileName parameter. I get the following error message when running maven install:

`
[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.3:generate (default) on project GridPackage-app: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.3:generate for parameter swaggerFileName: Cannot find 'swaggerFileName' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource -> [Help 1]`

**Comment by who** [comment]
@danjo830 Try removing the swaggerFileName node from your pom. The readme.md is currently reflecting the state of 3.1.4-SNAPSHOT, and swaggerFileName was added in 3.1.4-SNAPSHOT.

**Comment by danjo830** [comment]
Thanks, it works without the property in the pom. I didn't realize there was a newer version available.

**Comment by du-it** [comment]
Where can I get the 3.1.4-SNAPSHOT? I need a possibility to modify the output file name to sore the result for different api sources in seperate files.

**Comment by mwesselgk** [comment]
I need this feature too and the 3.1.4-SNAPSHOT is not available via the mentioned repo.
Can someone push the snapshot to repo?

**Comment by who** [comment]
@kongchen is the only one with the permissions to push snapshots and releases. I only have commit access.

@kongchen would you please update the snapshot ? Thanks!

**Comment by wenzhang-tradedoubler** [comment]
Yes, please do it. I am waiting for this new attribute to be available. Thanks in advance!

**Comment by mwesselgk** [comment]
@kongchen can you please provide snapshot or may be new release. thx

**Comment by rahul-winner** [comment]
any update on this? I'm still getting this error. Have we added support for "swaggerFileName" ? I'm using version 3.1.2

**Comment by hyp0th3rmi4** [comment]
Any update on this issue?

**Comment by hyp0th3rmi4** [comment]
Sorry my bad, I found 3.1.4 in Maven Central.
