### ISSUE TITLE
Does this plugin work with spring-boot application?

### ISSUE THREAD

**Issue by ameymehta** [kongchen/swagger-maven-plugin#345]
I have used this plugin with spring-mvc. I am now trying to use it with spring-boot application. It generates swagger.json, but it is not able to read the annotations from my controller files. Thus swagger.json does not have any of my APIs. I am using same swagger-core annotations.

**Comment by carlosjgp** [comment]
Yes it does supports it.

See possible related issue #218 and pull request #348

**Comment by ameymehta** [comment]
@carlosjgp Thank you for helping.
It turned out that my class did not have RequestMapping annotation.
Apparently the plugin needs @RequestMapping("") even though empty.
