### ISSUE TITLE
Travis randomly fails building PullRequests

### ISSUE THREAD

**Issue by carlosjgp** [kongchen/swagger-maven-plugin#346]
I created a PullRequest (#340) and it failed with oracle-jdk-8 profile.
Cancelling that PR and creating a new one (#342) failed all profiles

How can that be possible?

See:
https://github.com/kongchen/swagger-maven-plugin/pull/340
https://github.com/kongchen/swagger-maven-plugin/pull/342

**Comment by who** [comment]
I think I've addressed the issue by simplifying the travis build config. Could you please re-try ?

**Comment by carlosjgp** [comment]
Looks like this time everything worked! PullRequest #348 

But sadly... it doesn't ensures that the problem is fixed 😞 

Keep an eye on it! And... nice work 👍
