### ISSUE TITLE
@ApiParam annotations on interfaces not working

### ISSUE THREAD

**Issue by cen1** [kongchen/swagger-maven-plugin#358]
We use swagger annotations on interfaces and JAX-RS annotations on implementation classes to avoid annotation clutter. Swagger.json generated by native swagger-jersey2-jaxrs (1.5.9) produces the correct json but this maven plugin does not. Specifically, APIs are correctly detected but all @ApiParam information is missing (there are no parameter descriptions). So we get the full documentation but it's missing parameter info.

I tried to build the latest master and lifted the swagger dependency version to 1.5.9 but it still did not solve the problem. Therefore the bug must be caused by the plugin.

**Comment by panga** [comment]
@cen1, I have the exact same problem. Jersey and CXF are generating the docs correctly, but plugin not :(

**Comment by anujbhatia** [comment]
@kongchen please review the proposed fix for this issue

**Comment by cen1** [comment]
I can confirm the pull request works for me.
