### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by hwellmann** [kongchen/swagger-maven-plugin#364]
In version 3.1.3, the `generate` goal produces tons of logs like 

```
[INFO] Looking for path/query/header/form/cookie params in class com.fasterxml.jackson.databind.JsonNode
[INFO] trying extension com.github.kongchen.swagger.docgen.jaxrs.BeanParamInjectParamExtention@30a2308c
[INFO] Looking for body params in class com.fasterxml.jackson.databind.JsonNode
[INFO] Looking for path/query/header/form/cookie params in class java.lang.String
```

This is not very meaningful to users, so the messages should be suppressed or at least logged as DEBUG.

**Comment by ChazOriginal** [comment]
I agree with this.  The default logging should only show the classes that have been processed.

**Comment by Postremus** [comment]
Log output looks reasonable now in current master branch.

@who Please close
