### ISSUE TITLE
Duplicate "apiOperation" when 2 HTTP methods are on the same method

### ISSUE THREAD

**Issue by fstrudel** [kongchen/swagger-maven-plugin#377]
Hello,

I have a Spring MVC controller class annotated with:

``` java
 @ApiOperation(value = "Do something.")
 @RequestMapping(method = {RequestMethod.GET, RequestMethod.POST})
 public String doSomething(HttpServletRequest request, HttpServletResponse response) throws  Exception {
[...]
}
```

and the generated swagger file contains 2 paths (expected) but with the same `operationId` (not expected) so swagger editor complains about it: "Cannot have multiple operations with the same operationId: doSomething"

Would be nice to have the `operationId` being `httpMethod-methodName` instead of just `methodName`, what do you think?

Thanks
Fanny

**Comment by tjuchniewicz** [comment]
Duplicated by #354

**Comment by who** [comment]
This would be a tricky change based on how swagger core stores its operations map. It's definitely not impossible, though.

As a work-around, you could do something like this: 

```java
 @ApiOperation(value = "POST something.")
 @RequestMapping(method = {RequestMethod.POST})
 public String postSomething(HttpServletRequest request, HttpServletResponse response) throws  Exception {
this.doSomething([...]);
}
```

```java
 @ApiOperation(value = "GET something ")
 @RequestMapping(method = {RequestMethod.GET})
 public String getSomething(HttpServletRequest request, HttpServletResponse response) throws  Exception {
this.doSomething([...])
}
```

```java
 private String doSomething([...]) throws  Exception {
[...]
}
```

**Comment by fstrudel** [comment]
Yes of course (just did not want to change the original code, but will definitely work as well!)

**Comment by dimonv** [comment]
My apologies but using the method as a unique operation id is a bit dubious to my opinion.
It makes the OO approach in REST implementation impossible.
If you have e.g. an interface with GET method EmployeeManagement.getEmployees(String employerId);
```
EmployeeManagement.getEmployees(String employerId);
```
and would like multiple REST service interfaces to extend this interface, you will end up with "Cannot have multiple operations with the same operationId: getEmployees"

**Comment by Yannoo** [comment]
I agree with fstrudel. I real life, I need to attach two method http at the same controller method (and I can do it with Spring) even if it's not the best REST approach.

**Comment by charlescapps** [comment]
We've ran into this issue, too. The annoying thing is that if we have 2 methods in different Java classes (and different swagger Tags), it will just prepend numbers to the operation ID silently, which is a real problem. Is there a setting to just fail at compile time if you have 2 methods with the same operation ID, instead of silently renaming them?

**Comment by tjuchniewicz** [comment]
@who Why can't we change https://github.com/kongchen/swagger-maven-plugin/blob/master/src/main/java/com/github/kongchen/swagger/docgen/reader/SpringMvcApiReader.java#L164 from:

```java
String operationId = method.getName();
```

to

```java
String operationId = method.getDeclaringClass().getSimpleName() + "_" + method.getName() + "_" + requestMethod.name();
```

Works for me but maybe I'm missing something.

**Comment by liuxh0** [comment]
Hi all,

I know this is an old issue. I also ran into this problem.

Since operationId is optional (https://swagger.io/docs/specification/paths-and-operations/), can we skip generating this if not provided by user?
