### ISSUE TITLE
Add support for other SpringMVC annotations

### ISSUE THREAD

**Issue by aromanet42** [kongchen/swagger-maven-plugin#399]
Hello,

it would be great if you can add support for Spring MVC annotations such as @GetMapping, @PostMapping, etc.

Thanks a lot

**Comment by clarkdo** [comment]
+1

**Comment by Dema** [comment]
Also, it would be good if plugin will complain if it found @ApiOperation annotation and not found @RequestMapping. I've just spent couple of hours trying to understand why it doesn't include on of my classes  into json.

**Comment by timbuethe** [comment]
This is a duplicate of https://github.com/kongchen/swagger-maven-plugin/issues/451

**Comment by zbstof** [comment]
Please close this, this is fixed as per 3.1.6
