### ISSUE TITLE
How to generate a response with Custom List having a generic type class

### ISSUE THREAD

**Issue by smalik2043** [kongchen/swagger-maven-plugin#416]
I want to generate a response example with custom list having a generic type class. TestCustomList will be having a List of items

@ApiOperation(response = TestCustomList.class,responseContainer="List")

My Jax-Rs api return in following format

TestCustomList < Employee >  employeeCustomList;
return Response.status(Response.Status.OK).entity(testCustomList).build();

it is not generating array of employees in item, it displays empty items in example response

I have tried with below annotation first
@ApiOperation(response = Employee.class,responseContainer="List") 
but above is not working. It generated Employee test example, but I want it with custom list as have been stated at top. Is there any way how can I achieve the custom list having a resource class.

**Comment by who** [comment]
@smalik2043 

This is a limitation of swagger-core. To get around this, I usually recommend the creation of a shim class, like so: 


```

**Comment by smalik2043** [comment]
@who Thankyou it worked :)
