### ISSUE TITLE
@ApiParam collectionFormat parameter not working

### ISSUE THREAD

**Issue by gkozyryatskyy** [kongchen/swagger-maven-plugin#425]
Seems like when you trying to generate **swagger.json** with swagger-maven-plugin from annotations, swagger-maven-plugin skip `@ApiParam(collectionFormat = "csv")` and set ` "collectionFormat" : "multi"` by default. 

Is there a way to make swagger-maven-plugin to read `collectionFormat` parameter from `@ApiParam` annotation?

`collectionFormat` added in swagger annotations version 1.5.11 https://github.com/swagger-api/swagger-core/issues/1180

Also seem like it is something wrong here https://github.com/kongchen/swagger-maven-plugin/blob/master/src/main/java/com/github/kongchen/swagger/docgen/reader/AbstractReader.java#L441 `csv` is changed to `multi`. Do not sure it is really a problem, but maybe this link helps.

**Comment by kvasovan** [comment]
I'm using version 1.5.11. I implicitly pointed "csv":

`            @ApiParam(value = SwaggerConstants.LOG_EVENT_TYPE_PARAM_DESCRIPTION, collectionFormat = "csv") 
                @QueryParam("eventType") List<String> eventType,
`

But in swagger document I can see "multi", I'm wondering why is it happening?

**Comment by AlysG** [comment]
Same issue when I used @ApiImplicitParam (1.5.16 and 1.5.18). The generated swagger always used "multi"
` @ApiImplicitParam(name = "code", value = "code list", required = false, dataType="integer", collectionFormat="csv", allowMultiple=true, paramType = "query")`

**Comment by elder-cb** [comment]
I'm having the same issue with version 1.5.20.
`@ApiImplicitParam(name="samples", value="sample query param", paramType="query" required=false, dataType="string", collectionFormat="csv", allowMultiple=true, allowedValues="one,two,three")`
Stepping through the code, I realised that having dataType!="array" overrides the collectionFormat to null, and that later is set back to the default "multi"; unfortunately, if I set dataType to null or to array the items property doesn't get filled properly, as its type property would be set to "array".

Probably removing this line would allow us to use csv as collectionFormat in query params, but I haven't tried rebuilding the jar (yet):
[AbstractSerializableParameter.java:257](https://github.com/swagger-api/swagger-core/blob/6d6d46ea010f22a3ddc5172f97fe64908d1f66b1/modules/swagger-models/src/main/java/io/swagger/models/parameters/AbstractSerializableParameter.java#L257) `setCollectionFormat(null);`
```java
    public void setType(String type) {
        this.type = type;
        if(ArrayProperty.isType(type)) {
            if(getCollectionFormat() == null){
                setCollectionFormat(getDefaultCollectionFormat());
            }
        } else {
            setCollectionFormat(null);
        }
    }
```
