### ISSUE TITLE
Cannot assign configuration entry 'locations' with value 'com.xyz.my-project.v10.resources' of type java.lang.String to property of type java.util.List

### ISSUE THREAD

**Issue by rahul-winner** [kongchen/swagger-maven-plugin#441]
We are facing below issue with Swagger maven plugin. Although it is working on one or two machines and swagger json getting generated successfully.

Not sure if it has to anything with maven version. Most of us have maven version = 3.2.1 

**[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.4:generate (default) on project my-project-rest: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.4:generate for parameter locations: Cannot assign configuration entry 'locations' with value 'com.xyz.my-project.v10.resources' of type java.lang.String to property of type java.util.List**

Could anyone please help us! Thanks. Rahul

```
			<plugin>
				<groupId>com.github.kongchen</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>3.1.4</version>
				<configuration>
					<apiSources>
						<apiSource>
							<springmvc>false</springmvc>
							<locations>com.xyz.my-project.v10.resources</locations>
							<schemes>http,https</schemes>
							<host>http://localhost:8001</host>
							<basePath>/api</basePath>
							<info>
								<title>Swagger spec for REST API</title>
								<version>v1.0</version>
								<description>My Project REST API</description>
								<termsOfService>
									http://www.xyz.com/terms-and-conditions
								</termsOfService>
								<contact>
									<email>admin(@)testcompany.com</email>
									<name>Admin</name>
									<url>http://www.xyz.com</url>
								</contact>
								<license>
									<url>http://www.xyz.com/licenses/LICENSE-2.0.html</url>
									<name>Project Licence</name>
								</license>
							</info>
							<templatePath>${project.basedir}/src/swagger-templates/strapdown.html.hbs</templatePath>
							<outputPath>${project.basedir}/target/rest-docs/swagger-doc.html</outputPath>
							<swaggerDirectory>${project.basedir}/src/main/resources</swaggerDirectory>
						</apiSource>
					</apiSources>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

**Comment by JoepWeijers** [comment]
Hello Rahul, I think there is a mistake in your `<locations>` tags. It expects a list of `<location>`s, not a string, like so:
```
<locations>
  <location>com.xyz.my-project.v10.resources</location>
</locations>
```

**Comment by rahul-winner** [comment]
@JoepWeijers nopes. The tag name should be 'locations' only. Please read the specs
https://github.com/kongchen/swagger-maven-plugin#configuration-for-apisource

Apparently it is a maven issue. Can anyone please confirm it.

**Comment by viktorgunnarson** [comment]
@rahul-winner Did you even try @JoepWeijers's suggestion? He's right, it should be:
```
<locations>
  <location>com.xyz.my-project.v10.resources</location>
</locations>
```
See the example configuration: https://github.com/kongchen/swagger-maven-plugin#a-sample-configuration

**Comment by rahul-winner** [comment]
Thanks @viktorgunnarson @JoepWeijers 

I believe I found the the real issue. The new maven (MoJo) e.g. 3.3.9 is able to assign values to <locations> even if those are not defined within <location> tag. 

However, the older version of maven needs parameters whose type is ArrayList/List to be passed as set of tags. 

If one updates the version of maven to 3.3.9 and just uses <locations> then it works well.

Kindly confirm

**Comment by JoepWeijers** [comment]
Ah right, I did not know that Maven since version 3.3.9 supports comma separated values as input to configuration parameter of type List of String. My suggestion provides backwards compatibility with older versions of Maven.

I think that the documentation should (1) be consistent and (2; if chosen for the shorthand notation) mention that Maven 3.3.9 is required.

@smythie86 should we maybe revert your commit (c12b77b0f0e1f732140ee4ceac478cd0d439edab) to keep the documentation backward compatible with Maven < 3.3.9?

**Comment by rahul-winner** [comment]
thanks @JoepWeijers .. Yea, updating docs will help..

**Comment by spezifanta** [comment]
Thanks @viktorgunnarson. Saved me some pain 👍
