### ISSUE TITLE
jsonExampleValues 

### ISSUE THREAD

**Issue by magick93** [kongchen/swagger-maven-plugin#444]
According the readme, I should be able to use use `jsonExampleValues` to generate json examples. 
## POM 

```
...
<schemes>http</schemes>
<host>localhost:8080</host>
<basePath>/rest</basePath>
<jsonExampleValues>true</jsonExampleValues>
<templatePath>${basedir}/templates/strapdown.html.hbs</templatePath>
<outputPath>${basedir}/generated/document.html</outputPath>
<swaggerDirectory>${basedir}/generated/swagger-ui</swaggerDirectory>			                                   <swaggerApiReader>com.wordnik.swagger.jaxrs.reader.DefaultJaxrsApiReader</swaggerApiReader>
...
```

Version: 3.1.0

## Error

`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.0:generate (default) on project myproject: Unable to parse configuration of mojo com.github.kongchen:swagger-maven-plugin:3.1.0:generate for parameter jsonExampleValues: Cannot find 'jsonExampleValues' in class com.github.kongchen.swagger.docgen.mavenplugin.ApiSource -> [Help 1]
`

**Comment by danieleorler** [comment]
@magick93 you need to use a newer version of the plugin, `jsonExampleValues` ha been introduced after version 3.1.0. Latest version of this plugin is 3.1.4

**Comment by magick93** [comment]
Thanks @danieleorler
