### ISSUE TITLE
no support for @GetMapping @PostMapping @PutMapping @DeleteMapping

### ISSUE THREAD

**Issue by A-medDMK** [kongchen/swagger-maven-plugin#451]

**Comment by cesdperez** [comment]
I spent a good amount of time figuring out why my generated *swagger.json* was empty. That was the reason.

In case this happens to someone else, I just replaced all my annotations with `@RequestMapping(method = X)`

**Comment by samhalpa** [comment]
@cesdperez Yeah we had to do the same.

**Comment by gsugambit** [comment]
Any movement on this?

**Comment by gsugambit** [comment]
nvm this is fixed in latest version

**Comment by zbstof** [comment]
Please close this, this is fixed as per 3.1.6
