### ISSUE TITLE
multiple locations in one doc / swagger.yaml

### ISSUE THREAD

**Issue by xlthor** [kongchen/swagger-maven-plugin#468]
Version 3.1.4 from maven central:

If I put multiple locations like
     `<locations>xxx.core.jaxrs.apilogin.services;xxx.core.asset.jaxrs</locations>`

into pom.xml config section, I get a yaml w/o ANY API definition, just the info section.

If I change to

    `<locations>xxxx.core</locations>`

and thus letting him scan almost the entire source tree, the resullting outpput ptoperly contains all definitions from both packages above.

    `<configuration>
					<apiSources>
						<apiSource>
							<springmvc>false</springmvc>
							 <locations>xxx.core.jaxrs.apilogin.services;xxx.core.asset.jaxrs</locations>
			                <schemes>http,https</schemes>
			                <host>localhost</host>
			                <basePath>/services</basePath>`

Classes

`/**
 * @author vi-hong
 * Service Interface for API Login
 */
@Path("/v1/")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
@Api(value = "/services")
public interface ApiLoginService`

`/**
 * @author axel.amthor
 *
 */
@Path("/v1/")
@Produces(MediaType.APPLICATION_JSON + ";charset=utf-8")
@Api(value = "/services")
public interface AssetFrontService`

**Comment by who** [comment]
`locations` has been changed to use XML sub nodes, like so:

```
