### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by jblough** [kongchen/swagger-maven-plugin#485]
When annotating web services with @Api in a web app with both Java and Kotlin files, only the services in Java files show up in the generated swagger.json and swagger.yaml files.  Is this an issue with the plugin or a configuration issue on my part?  Thank you

**Comment by jblough** [comment]
Nevermind.  Apparently the issue was that the swagger-maven-plugin needed to be after org.jetbrains.kotlin plugin in the maven pom.xml file.

**Comment by adrik77** [comment]
@jblough I put swagger-maven-plugin after org.jetbrains.kotlin plugin in the maven pom.xml file and I'm still don't see kotlin resources in `swagger.json` file.
Could you share your configurations? 
Are you using spring or jax-rs?

Thanks in advance
