### ISSUE TITLE
multiple class locations results in an empty JSON file

### ISSUE THREAD

**Issue by ractoc** [kongchen/swagger-maven-plugin#493]
I have a setup where I have to specify two class files as locations. When I add either the package or one class file, I get a nice Swagger file. If I specify more then one class file, I only see the basic data in de swagger file as defined in the maven pom.
`
<plugin>
				<groupId>com.github.kongchen</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>3.1.0</version>
				<configuration>
					<apiSources>
						<apiSource>
							<springmvc>false</springmvc>
							<locations>com.gxwebmanager.novamedia.gdlfrontendrestservices.resource.AddressResource,com.gxwebmanager.novamedia.gdlfrontendrestservices.resource.RVVResource</locations>
							<schemes>https</schemes>
							<basePath>/web/rest</basePath>
							<info>
								<title>Generate RVV endpoint Swagger file</title>
								<version>v_1</version>
								<description>
									This swagger file contains all the endpoints needed to support the RVV through REST.
								</description>
							</info>
							<swaggerDirectory>${basedir}/target/generated/swagger/d2d</swaggerDirectory>
						</apiSource>
					</apiSources>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
`

**Comment by danieleorler** [comment]
In newer versions locations are defined like this:

```
<locations>
 <location>com...AddressResource</location>
 <location>com...RVVResource</location>
</locations>
```
I guess the documentation should be updated

**Comment by ractoc** [comment]
Yeah, that fixed it. I was using an older version of the plugin with the latest version of the configuration.

⁣Verzonden door BlueMail ​

Op 4 jul. 2017 09:44, om 09:44, Daniele Orler <notifications@github.com> schreef:
