### ISSUE TITLE
Question: does the `attachSwaggerArtifact` not work anymore?

### ISSUE THREAD

**Issue by starJammer** [kongchen/swagger-maven-plugin#501]
I tried adding `attachSwaggerArtifact` but it doesn't work. Where would I navigate to in order to get to this?

**Comment by azbarcea** [comment]
I use a `pom.xml` similar to the following, and I can confirm that `attachSwaggerArtifact` works as documented:
https://gist.github.com/azbarcea/05b55f0e660d1b4d335479cb602deb48

```xml
              <swaggerDirectory>${project.build.directory}/swagger-ui</swaggerDirectory>
              <!--
                  Do not use: swaggerFileName, as it will be used as classifier. 
                  In a multi-module project will have different classifier for different APIs
                -->
              <outputFormats>json</outputFormats>
              <attachSwaggerArtifact>true</attachSwaggerArtifact>
```

**`swagger-ui`**  is going to be used as classifier, even if a `${project.build.directory}/swagger-ui` (a longer path) is configured as `swaggerDirectory`

**Comment by dpursehouse** [comment]
I've found that if `outputFormats`  is not set, contrary to what the documentation says it does not default to `json` and no json files are generated.

**Comment by starJammer** [comment]
Thank you for the feedback guys. I'll try this but I ended up going in a different direction.
