### ISSUE TITLE
Multiple path on same method (JAX-RS) not generate correctly in swagger ui

### ISSUE THREAD

**Issue by TomML100** [kongchen/swagger-maven-plugin#509]
Hi,
How could generate multiple path on same method in **swagger ui** ?

What i did in resource :
@Path("/api/{a: v1|v2}/user")

Expected result show in swagger ui:
/api/v2/user
/api/v1/user

Current result in swagger ui :
/api/{a}/user

Could you advise ?

Thank you

**Comment by grimly** [comment]
Your annotation is a path parameter with a pattern check.
If one would write `@Path("/{a:v[0-9]+")` then you would not be able to generate all possible URLs since my is not finite.

**Comment by TomML100** [comment]
ok, thank for advise 👍
