### ISSUE TITLE
Problem with operationId generation

### ISSUE THREAD

**Issue by cunhazera** [kongchen/swagger-maven-plugin#529]
We have some problem: the operationId is generated based on the endpoint method name.
So when we have two or more methods with the same (even in different classes) name it fails.

Is there some way to define roles to operationId generation?

We're currently using the 3.1.5 version.

**Comment by who** [comment]
You can use the `nickname` option to override the operationId. http://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiOperation.html#nickname()

**Comment by Flomix** [comment]
mmh i have the same problem and nickname doesn't help me. Neither `nickname=""` nor `nickname = null` works to remove the operationId, it just falls back to the default.

I would either need the class name additionally, or variables, or any other means to remove the operationId :-/ Right now I have to add a custom filter that removes all "operationId" fields from the JSON, which feels bad.

**Comment by mireczatko** [comment]
the best here will be ability to turn off generating operationId completely and add {{path}} token to operationIdFormat
