### ISSUE TITLE
JaxrsReader#updateTagDescriptions slow

### ISSUE THREAD

**Issue by set321go** [kongchen/swagger-maven-plugin#534]
I use the gigaSproule/swagger-gradle-plugin and ran into problems recently of the plugin being really slow after updating the versions. I think i have isolated the issue to the `JaxrsReader#updateTagDescriptions` which runs for every `ApiOperation` annotated method in the class, the `Reflections("").getTypesAnnotatedWith(SwaggerDefinition.class)` is pretty slow in my case as its scanning the entire gradle classpath which is compounded by the fact its done for every iteration of the loop.

It should be possible to cache the results of 
```
        for (Class<?> aClass: new Reflections("").getTypesAnnotatedWith(SwaggerDefinition.class)) {
            SwaggerDefinition swaggerDefinition = AnnotationUtils.findAnnotation(aClass, SwaggerDefinition.class);

            for (io.swagger.annotations.Tag tag : swaggerDefinition.tags()) {

                String tagName = tag.name();
                if (!tagName.isEmpty()) {
                    tags.put(tag.name(), new Tag().name(tag.name()).description(tag.description()));
                }
            }
        }
```
This will speed things up and reduce duplication
Ideally I could set some properties that will control the extent of this scan

**Comment by clounie** [comment]
Having the same problem, thanks for doing this.
