### ISSUE TITLE
skipSwaggerGeneration / swagger.skip dosen't actually skip

### ISSUE THREAD

**Issue by amohanse** [kongchen/swagger-maven-plugin#540]
Tried using the settings inside the plugin configuration and also in the maven command like 
mvn clean package -DskipSwaggerGeneration=true -Dswagger.skip=true
dosen't seems to skip the document generation, any known issues / workaround available?

**Comment by amohanse** [comment]
It works in version 3.1.3

**Comment by dnltsk** [comment]
I think you need to reorder your command parameters.
´´´mvn -h
usage: mvn [options] [<goal(s)>] [<phase(s)>]´´´

**Comment by jfairley** [comment]
There's no fix version attached to this issue, but I wanted to echo that I had the same issue as @amohanse. `-Dswagger.skip=true` did not work for me in `3.1.5`, but now works fine in `3.1.7`. Clearly something got fixed along the way.

Also, @dnltsk, `mvn test -Dswagger.skip=true` and `mvn -Dswagger.skip=true test` are effectively the same thing, in other words, both will either work or not work.

**Comment by jfairley** [comment]
Ah ok. It seems that the functionality (`-Dswagger.skip=true`) didn't actually exist at all until 3.1.6: https://github.com/kongchen/swagger-maven-plugin/commit/f2ca801693bbc796af07f651fe3947491d5680a6

Funny that 

> It works in version 3.1.3

`¯\_(ツ)_/¯`
