### ISSUE TITLE
dataTypeClass in @ApiImplicitParam is ignored

### ISSUE THREAD

**Issue by dcp65** [kongchen/swagger-maven-plugin#542]
I'm not sure if this is an issue in the swagger-maven-plugin or in swagger-core.

I am trying to document a Spring MVC application using Swagger annotations. 

I have a number of POST APIs that send a JSON object in the request body. Because the class of the body cannot be easily inferred from the code, I am calling it out using an `@ApiImplicitParam` annotation with a `dataTypeClass` attribute, as shown in this example:

```java
@Api(tags = "Widgets")
@Controller
public class WidgetController
{
@ApiOperation(value = "createWidget", notes = "Creates a widget")
    @ApiImplicitParams(
            {
            @ApiImplicitParam(paramType = "body", 
                name = "body", 
                value = "A Widget object", 
                required = true,
                dataTypeClass = WidgetModel.class)}
    )
    @RequestMapping(value = "/widgets", method = POST)
    public String createWidget(
    
    ...
   
   );
}
```
When the swagger.json is generated using the swagger-maven-plugin, it seems that the value of `dataTypeClass` is ignored. I expect a `WidgetModel` to be added to the definitions,  but I get `WidgetController` instead.

```javascript
{
  "paths": {
    "/widgets": {
      "post": {
        "tags": [
          "Widgets"
        ],
        "summary": "createWidget",
        "description": "Creates a widget",
        "operationId": "createWidget",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": " A Widget object",
            "required": true,
            "schema": {
              "$ref": "#/definitions/WidgetController"
            }
          }
        ]
      }
    }
  }
}
```

**Comment by bratwurzt** [comment]
I have a workaround, if anybody's interested: in place of `dataTypeClass = WidgetModel.class` set `dataType = "whole.name.of.class.WidgetModel"`
Also did a MR for `dataTypeClass = WidgetModel.class`
