### ISSUE TITLE
Please add null check for cls variable i am getting null pointer error from this method 

### ISSUE THREAD

**Issue by sidlingappa** [kongchen/swagger-maven-plugin#547]
https://github.com/kongchen/swagger-maven-plugin/blob/2d6f12d21eb0c4b35826bb121bcbcf0884c27077/src/main/java/com/github/kongchen/swagger/docgen/spring/SpringSwaggerExtension.java#L218

**Comment by who** [comment]
PRs are welcome if you'd like to contribute , @sidlingappa :)
