### ISSUE TITLE
verbose output

### ISSUE THREAD

**Issue by bbarroux** [kongchen/swagger-maven-plugin#559]
First thanks for the plugin, it works great. 

However, maybe I'm doing something wrong, but during the maven build, the full swagger.json is output to the console, which is quite verbose. Is there a way to prevent this logging output?

**Comment by viktorgunnarson** [comment]
This has been fixed (see #486 ), but the fix is not yet released. As far as I know, there is no simple way of disabling this in 3.1.5.

**Comment by viktorgunnarson** [comment]
Duplicate of #486

**Comment by bbarroux** [comment]
Thanks, sorry for the noise, didn't see the duplicate.
