### ISSUE TITLE
A required class missing while executing com.github.kongchen:swagger-maven-plugin:3.1.0:generate: jarava

### ISSUE THREAD

**Issue by BrianJVarley** [kongchen/swagger-maven-plugin#560]
Hi @kongchen,

I ran into this problem running the swagger-maven-plugin on a new development machine.
Running any of the other mvn commands runs successfully on the machine.

But running this plugin with command - `mvn compile -Dbuild=swagger -DskipTests=true` fails with the below error summary on the `swagger-maven-plugin:3.1.0:generate` build step.

I tried changing the plugin version from `3.1.1` to `3.1.2` as referenced in this answer to no avail:

https://github.com/kongchen/swagger-maven-plugin/issues/318

Do you have any ideas why the generate step is failing in this instance?

**Error Summary:**

`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.0:generate (default) on project ChatAPI: Execution default of goal com.github.kongchen:swagger-maven-plugin:3.1.0:generate failed: A required class was missing while executing com.github.kongchen:swagger-maven-plugin:3.1.0:generate: javax/xml/bind/annotation/XmlRootElement`

**Complete Error Log:**

https://hastebin.com/oxeyicayik.pas

**Comment by BrianJVarley** [comment]
Solved it by `--add-modules java.xml.bind`  as missing EE module in my Java SE 9 version. 

https://stackoverflow.com/a/43574427

**Comment by imechemi** [comment]
After checking the StackOverflow, I found the cause of the issue, which in my case was due to Java version mismatch between my machine and the project. Changing the Java version to the project's requirement resolved the issue for me.
