### ISSUE TITLE
How to use @ApiParam for GET request with SpringMVC?

### ISSUE THREAD

**Issue by ousui** [kongchen/swagger-maven-plugin#581]
We know that SpringMVC can package parameters to an Object with an GET request.
I use swagger's @ApiParam for the Request Object, but it was an Request Body not normal query parameters.
```
public ResponseEntity query(@ApiParam ApiRequest request) { ...... }
```
This Request Object has many properties, I used @ApiModelProperty for the Object.

**Comment by stevegomez17** [comment]
OK thanks

**Comment by Postremus** [comment]
fixed by #671 
The properties of the ModelAttribute need to be annotated as ```@ApiParam``` however, since they will later be normal query parameters in the doc.

**Comment by lpc0828** [comment]
@Postremus Sorry, not particularly clear, as in the question [ousui](https://github.com/ousui), I expected custom types to generate interface documentation as query parameters, but now I can only generate documentation as request body
eg：
public ResponseEntity query(@ApiParam ApiRequest request) { ...... }

expect:
![image](https://github.com/kongchen/swagger-maven-plugin/assets/2051916/906a210f-b12e-424e-949c-30d71117a182)

but actual：
![image](https://github.com/kongchen/swagger-maven-plugin/assets/2051916/59f91f1a-e710-4dab-b935-9562403f8dc0)

**Comment by ousui** [comment]
> 

大概是请求对象内部属性需要 `@ApiParam` 注解。
