### ISSUE TITLE
plugin not parsing any class files for unknown reason

### ISSUE THREAD

**Issue by soerenGer** [kongchen/swagger-maven-plugin#611]
Hi,

I'm new to the plugin and are now trying since hours to generate any swagger-output. And really don't know why.
Environment is command line (windows) and eclipse, but I try to fiddle it right on the command line first.

As a starting point I downloaded the example project which worked well out of the box. Modified my small pom.xml and after some tries I got the plugin working, however now classes are found. And YES: I checked that target/classes does contain my .class files.

The plugin section is quite small now:

				<groupId>com.github.kongchen</groupId>
				<artifactId>swagger-maven-plugin</artifactId>
				<version>${swagger-maven-plugin-version}</version>
				<configuration>
					<apiSources>
						<apiSource>
							<springmvc>false</springmvc>
							<locations>creditshelf.ers.api.service</locations>
							<info>
								<title>Entity Recognition Service API</title>
								<version>v1</version>
							</info>
							<outputFormats>json</outputFormats>
							<swaggerDirectory>generated/swagger-ui</swaggerDirectory>
						</apiSource>
					</apiSources>
				</configuration>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>generate</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

Additionally I added quite some dependencies from the example's pom.xml

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>servlet-api</artifactId>
			<version>2.5</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-jetty-http</artifactId>
			<version>${jersey-version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.core</groupId>
			<artifactId>jersey-server</artifactId>
			<version>${jersey-version}</version>
		</dependency>

		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-servlet-core</artifactId>
			<version>${jersey-version}</version>
		</dependency>

		<!-- required by the maven-swagger-plugin -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>${logback-version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>${logback-version}</version>
			<scope>compile</scope>
		</dependency>

	<properties>
		<apache-commons-version>2.6</apache-commons-version>
		<joda-time-version>2.9.9</joda-time-version>
		<log4j-version>2.11.0</log4j-version>
		<neo4j-driver-version>1.5.2</neo4j-driver-version>
		<jersey-version>2.27</jersey-version>
		<jetty-version>9.4.0.v20161208</jetty-version>
		<logback-version>1.0.1</logback-version>
		<swagger-version>1.5.3</swagger-version>
		<swagger-maven-plugin-version>3.1.1</swagger-maven-plugin-version>
	</properties>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Now when I run "mvn compile" my output looks like this (I tried also "mvn -e -X clean compile swagger:generate" for a clean run, same result):

[INFO] --- swagger-maven-plugin:3.1.1:generate (default-cli) @ ers-service ---
[DEBUG] Configuring mojo com.github.kongchen:swagger-maven-plugin:3.1.1:generate from plugin realm ClassRealm[plugin>com.github.kongchen:swagger-maven-plugin:3.1.1, parent: sun.misc.Launcher$AppClassLoader@33909752]
[DEBUG] Configuring mojo 'com.github.kongchen:swagger-maven-plugin:3.1.1:generate' with include-project-dependencies configurator -->
[DEBUG]   (s) springmvc = false
[DEBUG]   (s) locations = creditshelf.ers.api.service
[DEBUG]   (s) title = Entity Recognition Service API
[DEBUG]   (s) version = v1
[DEBUG]   (s) info = io.swagger.models.Info@afee3ee3
[DEBUG]   (s) outputFormats = json
[DEBUG]   (s) swaggerDirectory = generated/swagger-ui
[DEBUG]   (s) apiSources = [com.github.kongchen.swagger.docgen.mavenplugin.ApiSource@664e848c]
[DEBUG] -- end configuration --
[DEBUG] [com.github.kongchen.swagger.docgen.mavenplugin.ApiSource@664e848c]
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 2 ms to scan 1 urls, producing 1 keys and 1 values
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**There are however a number of files available!**

$ find target/classes/
target/classes/
target/classes/creditshelf
target/classes/creditshelf/ers
target/classes/creditshelf/ers/api
target/classes/creditshelf/ers/api/entities
target/classes/creditshelf/ers/api/entities/Company.class
target/classes/creditshelf/ers/api/entities/CompanyProbabilityTuple.class
target/classes/creditshelf/ers/api/service
target/classes/creditshelf/ers/api/service/CrudMethodsInterface$IdType.class
target/classes/creditshelf/ers/api/service/CrudMethodsInterface.class
target/classes/creditshelf/ers/api/service/MaintenanceMethodsInterface.class
target/classes/creditshelf/ers/service
target/classes/creditshelf/ers/service/CrudMethodsService.class
target/classes/logback.xml

**And just to show one of the classes**
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[...]
@Path("entity")
@Api(value = "customers", description = "RESTful API to provide CRUD methods to the ERS' node entities")
@Produces("application/json")
public class CrudMethodsService implements CrudMethodsInterface {

	@PUT
	@ApiOperation(value = "Create a new Company entity", notes = "CREATE: This method must be called to create a new entity. The call to this method is imperative, i.e. it will always create a new company entity node.", response = Company.class)
	@Path("/")
	@Produces(MediaType.APPLICATION_JSON)
	public Company createCompany(Company company) {
		// TODO Auto-generated method stub
		return null;
	}
[...]

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

So right here I'am quite desperate now: Maven works fine, the file structure is there, the plugin starts and does "something" but anything else fails without a single comment.

Any ideas on this, would be greatly welcome ,-) ?

Regards,
Sören

**Comment by Postremus** [comment]
Your currently used version of swagger-maven-plugin (3.1.1) is quite old. Could you please try updating, if possible, to the newest release version (3.1.7)?
You might also want to add an empty `@ApiParam` annotation to your `company` body parameter, so that the plugin actually generates documentation for the `Company` class (see #606).

This might also be related to #276 and #261, since in these issues also no documentation is generated.

**Comment by soerenGer** [comment]
Hi Postremus, tried the 3.1.7, upgraded the use of swagger-core to 1.5.19 as well and also added @ApiParam as suggested. The output from the maven log looks a little different, I can see that individual classes are scanned, the output however still is not created.

So I tried the other way round: I threws some basic classes from my project into the sample project and again started the mvn compile: To my surprise now neither the sample classes nor my own classes get parsed! So it looks like something scres up the parses but nothing is shown in the log, which makes it impossible for me to solve the root cause ,-/

The output now looks like this:


[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 78 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 15 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] adding extension io.swagger.jersey.SwaggerJerseyJaxrs@76d72b5b
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 0 ms to scan 1 urls, producing 1 keys and 1 values
[DEBUG] going to scan these urls:
file:/C:/Users/soeren/git/creditshelf-knowledge-graph/ers_service/EntityRecognitionService/target/classes/
[INFO] Reflections took 17 ms to scan 1 urls, producing 1 keys and 1 values

**Comment by soerenGer** [comment]
Hi Postremus, thanks again for looking after this issue!

I changed the locations tag, didn't notice the tag syntax changed. So now it's processing the sample classes again, but still no output. And yes, I checked to correct output directory ,-) It's generating the files every time - but without my classes.

**Comment by soerenGer** [comment]
Okay, closing this issue. After trying again over and over I rebuild most things from scratch and this time it worked. Probably I finally oversaw anthing in respect to pathes source paths or so. But thanks for the help, it seems to work now ,-))

**Comment by vamshichanda-git** [comment]
Hi @soerenGer,
I'm facing a similar issue. What was that resolved the issue in your case?

Thanks.

**Comment by PiotrChlopicki** [comment]
Hi there,
I'm facing this problem after upgrading spring boot to version 3.3.x and maven 3.9.x. Do you have maybe idea what might happen? @Postremus 

[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.8:generate (default) on project XXX-app: Execution default of goal com.github.kongchen:swagger-maven-plugin:3.1.8:generate failed: A required class was missing while executing com.github.kongchen:swagger-maven-plugin:3.1.8:generate: javax/xml/bind/annotation/XmlRootElement
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.kongchen:swagger-maven-plugin:3.1.8
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
...
Number of foreign imports: 1
import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
