### ISSUE TITLE
Using @Extension on Info does not seem to work

### ISSUE THREAD

**Issue by fraisse** [kongchen/swagger-maven-plugin#617]
Hello,

I have configured a swagger specification generation using the `@SwaggerDefinition` annotation:

```
@SwaggerDefinition(
    info = @Info(title = "The API", version = "V1.0", extensions = {
        @Extension(name = "logo", properties = {
            @ExtensionProperty(name = "url", value = "logo url")
        })
    }),
    schemes = {SwaggerDefinition.Scheme.HTTPS}
)
```

I've tried also with `"x-logo"` as name.

After the generation, I've got only the `title` and the `version` but not the extension:

```
{
  "swagger" : "2.0",
  "info" : {
    "version" : "V1.0",
    "title" : "The API"
  },
  ...
}
```

Did I missed something?

Thanks in advance.

**Comment by venkatukl** [comment]
Hi Team,

Any updates on this issue? Is there a workaround for this issue?

I am facing the same issue [version# 3.1.17] and I am not seeing the extension generated in swagger yaml. I tried with both extension name as "x-test" and the property name as "x-test-property". 

"extension" on APIOperation annotation seems to be working though.

**Comment by Postremus** [comment]
This is currently not implemented for the Info annotation, see:
https://github.com/kongchen/swagger-maven-plugin/blob/master/src/main/java/com/github/kongchen/swagger/docgen/mavenplugin/ApiSource.java#L190

Also, there does not seem to be any workaround for this at the moment.
