### ISSUE TITLE
securityDefinition name overriden

### ISSUE THREAD

**Issue by PabloToledano** [kongchen/swagger-maven-plugin#650]
When using a securityDefinition.json file, field name is overriden with the object name:

securityDefinition.json
{
  "name" : {
    "type" : "apiKey",
    "name" : "particularName",
    "in" : "header"
  }
}

gets converted to:
{
  "name" : {
    "type" : "apiKey",
    **"name" : "name",**
    "in" : "header"
  }
}

I think the problem is in:

SecurityDefinition.java
`while (securityDefinitionNameIterator.hasNext()) {
                String securityDefinitionName = securityDefinitionNameIterator.next();
                JsonNode securityDefinition = tree.get(securityDefinitionName);
                securityDefinition = ((ObjectNode) securityDefinition).put("name", securityDefinitionName);
                securityDefinitions.add(securityDefinition);
  }`

Would it be right to put the name only if there is no one present?. In case this is right I will prepare a pull request.

Thanks,
best regards.

**Comment by PabloToledano** [comment]
You are right indeed. I must have missed this one. Thanks for telling me and for the pull request, it is a more complete solution than mine.

**Comment by who** [comment]
Closing as duplicate
