### ISSUE TITLE
SecurityDefinition.json is overwritting name with security-name

### ISSUE THREAD

**Issue by Auskennfuchs** [kongchen/swagger-maven-plugin#664]
When using the securityDefinition.json and defining an apiKey security entry you are not able to set the name inside. This value gets overwritten by the security entries name.
Example:
`{
  "jwtAuth": {
    "type": "apiKey",
    "name": "Authorization",
    "in": "header"
  }
}`

results in 
`securityDefinitions:
  jwtAuth:
    type: "apiKey"
    name: "jwtAuth"
    in: "header"`

correct output should be:
`securityDefinitions:
  jwtAuth:
    type: "apiKey"
    name: "Authorization"
    in: "header"`

This problem wasn't shown in the tests because the same string is used in both places.

**Comment by Postremus** [comment]
This is, if I see correctly, a duplicate for #616 (and #650). I had opened PR #644 to fix this.

**Comment by who** [comment]
https://github.com/kongchen/swagger-maven-plugin/pull/644 has been merged to address this issue.
