### ISSUE TITLE
springmvc: @ResponseStatus annotation for CREATED results in doubled response description

### ISSUE THREAD

**Issue by mbr74** [kongchen/swagger-maven-plugin#716]
Generated result:
```
...
"responses" : {
  "200" : {
    "description" : "successful operation",
      "schema" : {
      "$ref" : "#/definitions/ResultDto"
    }
  },
  "201" : {
    "description" : ""
  }
}
...
```

Expected result:
```
...
"responses" : {
  "201" : {
    "description" : "successful operation",
      "schema" : {
      "$ref" : "#/definitions/ResultDto"
    }
  }
}
...
```

**Comment by bratwurzt** [comment]
I added my own PR since https://github.com/kongchen/swagger-maven-plugin/pull/731 did not resolve the issue completely.

**Comment by a-n710** [comment]
That does not look like a correct fix in my opinion, as it clears description and schema of the response.
I've got this, using #743 version
`        "responses" : {
          "201" : {
            "description" : ""
          }
        }`

**Comment by bratwurzt** [comment]
It doesn't clear the description of response 201, it creates a new one. Your commit replaces the http code and reason (description) of whole 200 response. Why would we assume 201 (or any non-200 2xx response) has the same response scheme as autogenerated 200? Also, where would we define the scheme in ResponseStatus annotation, when response class is RequestEntity<?>? 

If you need a scheme in response 201, add it in ApiResponse(201).

My fix removes 200 only when:
1. operation does not contain ApiResponse(200) and contains ApiResponses(2xx)
and
2. operation does not yet contain ApiResponse(201) and ResponseStatus is 201

Example of #731 not working is when there are any existing ApiResponses.

**Comment by a-n710** [comment]
I do no use ApiResponse in my code, so I have not considered that. Will recheck. 

The thing is that by design ResponseStatus annotation overrides response code set by other means, so even if I try to return 200 using `ResponseEntity.ok(...)`, given that annotation is set, controller will reply necessary data with 201 code. This behaviour is reflected in #731. Maybe the changes need to be combined to cover all cases. 

As for the schema setting - in most cases it is automatically determined when you specify class inside ResponseEntity's generic.

**Comment by bratwurzt** [comment]
> The thing is that by design ResponseStatus annotation overrides response code set by other means, so even if I try to return 200 using ResponseEntity.ok(...), given that annotation is set, controller will reply necessary data with 201 code.

This is a very good point. Will refactor my commit to reflect this. Also for scheme.

**Comment by bratwurzt** [comment]
@a-n710 Commited changes; override of 201 over 200 now retains existing schema and headers.

**Comment by a-n710** [comment]
201 was provided merely as example, this should work with `@ResponseStatus(HttpStatus.ACCEPTED)` or any other option. 

As far as I can see, if we merge our PRs, result should satisfy both parties: if ApiResponses is specified, we ignore ResponseStatus and assume that definition in ApiResponses is complete. Otherwise we go with my approach. The only case that will not be covered by this approach - when ApiResponses is present but does not contain any 2xx codes, which, as I understand, should not be too common.

**Comment by bratwurzt** [comment]
> As far as I can see, if we merge our PRs, result should satisfy both parties: if ApiResponses is specified, we ignore ResponseStatus and assume that definition in ApiResponses is complete.
I don't think so - the whole point of this MR is to remove/replace default 200 response (which is added in `com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader#parseMethod`) in special cases where you don't want 200 at all. For example - combination of ResponseStatus(201) and ApiResponse(204) is perfectly legitimate: 201 is default, 204 is a special case. I don't think we should override scheme or description in case of 204 with the one from 200 - no content has no content. 
Also the case which you pointed out at the end - if you set any ApiResponses and have set default on ResponseStatus, it will be ignored.

**Comment by a-n710** [comment]
```
    @ResponseStatus(code = HttpStatus.ACCEPTED)
    public ResponseEntity<String> test1()
...
    @ResponseStatus(code = HttpStatus.ACCEPTED)
    public String test2()
```

from my perspective both of these methods should result in 
```
        202:
          description: "successful operation"
          schema:
            type: "string"
```

At the same time, both of these
```
    @ApiResponses({@ApiResponse(code = 201, message = "201 message"), @ApiResponse(code = 409, message = "conflict message")})
    public String test4()
...
    @ResponseStatus(code = HttpStatus.CREATED)
    @ApiResponses({@ApiResponse(code = 201, message = "201 message"), @ApiResponse(code = 409, message = "conflict message")})
    public String test5()
```
should result in 
``` 
        201:
          description: "201 message"
          schema:
            type: "string"
        409:
          description: "conflict message"
```

and finally, 
```
    @ResponseStatus(code = HttpStatus.OK)
    @ApiResponses({@ApiResponse(code = 201, message = "201 message"), @ApiResponse(code = 409, message = "conflict message")})
    public String test6()
```
should also be converted into 
``` 
        201:
          description: "201 message"
          schema:
            type: "string"
        409:
          description: "conflict message"
```

The last one is a little controversial and can be expected to become
``` 
        200:
          description: "successful operation"
          schema:
            type: "string"
        201:
          description: "201 message"
        409:
          description: "conflict message"
```
but I think that if someone is explicitly specifying api responses there is no reason to avoid defining all of them, including the 200 one, if needed. 
Currently you PR fails to specify `type: string` in all cases and duplicates status code in the test1-test2 block .
