### ISSUE TITLE
Deploy Swagger UI

### ISSUE THREAD

**Issue by cbrom** [kongchen/swagger-maven-plugin#833]
Hello, thanks for the plugin. I can generate swagger.json and the document.html based on the tamplate on the provided example repo.

But I was wondering how one could deploy this swagger ui like [Swagger UI](https://petstore.swagger.io/?_ga=2.254073352.1494904042.1598177894-1659687769.1598085246)

Thanks

**Comment by coryellenberger** [comment]
This plugin generates an html webapp. You can deploy the generated app with multiple tools; as long as you can serve the html.

This plugin wouldn't have anything to do with that deployment process or a deployment of Swagger UI.

Where you can find/download Swagger UI to deploy it as well as any documentation: https://swagger.io/tools/swagger-ui/

**Comment by cbrom** [comment]
Alright. Got it!
Thanks!
