### ISSUE TITLE
basepath value repeats in paths section 

### ISSUE THREAD

**Issue by mercanil** [kongchen/swagger-maven-plugin#836]
I am working on a spring boot project. I followed the doc and added basepath but in the **paths** section **basepath** repeats again. I wanted to remove repeating parts from paths but it doesn't work with basePath

```
<apiSource>
  <springmvc>true</springmvc>
  <locations>
      <location>com.XXX</location>
  </locations>
  <swaggerDirectory>${swagger.directory}</swaggerDirectory>
   <swaggerFileName>${swagger.filename}</swaggerFileName>
  <swaggerApiReader>com.github.kongchen.swagger.docgen.reader.SpringMvcApiReader</swaggerApiReader>User
  <outputFormats>yaml</outputFormats>
  <attachSwaggerArtifact>true</attachSwaggerArtifact>
   <basePath>/c/u/</basePath>
</apiSource>
```
````
swagger: "2.0"
info:
  description: "Desc"
  version: "1.1.1"
  title: "Title"
basePath: "/c/u/"
paths:
  /c/u/:
    get:
      summary: "Get list of registered users"
````

Thank You

**Comment by DavidSwiftHadoop** [comment]
I found in this case I still get the basePath from the first apiSource in the second and I don't want *any* basePath in the second one. I tried specifying it as empty as well the second time, but that didn't help.
                <configuration>
                    <apiSources>
                        <apiSource>
                            <locations>
                                <location>com.company.web.LocalApiVersion1</location>
                            </locations>
                            <schemes>
                                <scheme>http</scheme>
                                <scheme>https</scheme>
                            </schemes>
                            <basePath>/product/api</basePath>
                            <info>
                                <title>Our REST API</title>
                                <version>${project.version}</version>
                                <description>
                                    This REST API provides remote access to the server.
                                </description>
                                <license>
                                    <url>https://www.gnu.org/licenses/agpl-3.0.en.html</url>
                                    <name>GNU Affero General Public License (AGPL), Version 3</name>
                                </license>
                            </info>
                            <swaggerDirectory>${project.build.directory}/swagger</swaggerDirectory>
                        </apiSource>
                        <apiSource>
                            <locations>
                              <location>com.company.web.LocalWithoutBasePathOnlyHttpsAndDifferentLicenseApiVersion1</location>
                            </locations>
                            <schemes>
                                <scheme>https</scheme>
                            </schemes>
                            <info>
                                <title>Another REST API</title>
                                <version>${project.version}</version>
                                <description>
                                    This REST API provides another variant of access to the server.
                                </description>
                                <license>
                                    <name>The Apache Software License, Version 2.0</name>
                                </license>
                            </info>
                            <swaggerDirectory>${project.build.directory}/swagger</swaggerDirectory>
                            <swaggerFileName>different-swagger</swaggerFileName>
                            <attachSwaggerArtifact>true</attachSwaggerArtifact>
                        </apiSource>
                    </apiSources>
                </configuration>
