### ISSUE TITLE
using swagger-maven with POJOs and servlets?

### ISSUE THREAD

**Issue by cesarpachon** [kongchen/swagger-maven-plugin#89]
hello! I am playing with a simple REST server using only servlets and custom POJO's that act as resources.. not using Jersey nor any other RESTful library right now. I wonder if I can use swagger-maven to generate api doc for my custom objects? or it is mandatory to use those jersey anotations? thanks!

**Comment by simonetripodi** [comment]
Hi there @kongchen and @cesarpachon ,
apologise for resurrecting a long-time dead thread, but I was not able to find any reference on an open-source _swaggerApiReader_ to read plain old Servlets...
Are you aware of it? After googling for a while I found no useful info, would you be available to share any link, please? TIA! :)
