### ISSUE TITLE
@BeanParam does not seem to work

### ISSUE THREAD

**Issue by jianlans** [kongchen/swagger-maven-plugin#90]
I have parameters marked as @BeanParam in the source which does not get generated properly in the Swagger JSON output. E.g. the param is defined as:
@BeanParam CommonParam commonParam
while CommonParam as:
public class CommonParam {

	@QueryParam("pageSize")
	@ApiParam(value="Results page size", required=false, defaultValue="25")
	private Integer pageSize = null;
...
}

While the generated JSON shows CommonParam as a body with type CommonParam instead of expanding CommonParam to include all the params:
        "name" : "body",
        "required" : false,
        "type" : "CommonParam",
        "paramType" : "body",
        "allowMultiple" : false

Is @BeanParam not supported yet? I am on swagger-maven-plugin version 2.3. BTW, @BeanParam works properly with run-time generated swagger doc. Any suggestion?

**Comment by who** [comment]
I am also seeing this issue.

**Comment by kongchen** [comment]
Please try 3.0.1-SNAPSHOT

**Comment by ravirsagar** [comment]
This is still not working for me. I'm using 3.1.2 with swagger 1.5.4. My parent java bean fields are  annotated with @FormParam and I'm using @BeanParam to use this class in my resource class. The generated json doesn't show the reference to the  bean definition instead it includes all the fields as parameters. Am I missing something?
