### ISSUE TITLE
How to exclude classes from becoming schemas?

### ISSUE THREAD

**Issue by gpsfl** [kongchen/swagger-maven-plugin#900]
In our web application we have some endpoints which look like this:

```java
    @POST
    @Path("/test")
    public Response test(com.google.gson.JsonObject body) {}
```

This prompts the swagger-maven-plugin to create a schema for the JsonObject class from the gson library.

How can we exclude certain classes / packages from becoming schemata?

**Comment by marcogrcr** [comment]
@gpsfl Based on the [configuration docs](https://github.com/kongchen/swagger-maven-plugin?tab=readme-ov-file#configuration-for-apisource), your best bet may be to move the test controllers you don't want to a separate java package and only specify the ones you want in the `<locations>` element.

**Comment by gpsfl** [comment]
@marcogrcr This one is just an example. We have multiple regular calls which take JsonObject because we don't know the structure from the beginning or process it dynamically later on. It would be really helpful to have a way of excluding packages/classes from being converted to models.

**Comment by marcogrcr** [comment]
@gpsfl I see. Given that the last commit on this project was almost 4 years ago (https://github.com/kongchen/swagger-maven-plugin/commit/e4cf3af6ed4a4987b2269a05b7037549bc4a5511), you'll probably want to consider an alternative plugin. See https://github.com/kongchen/swagger-maven-plugin/issues/550#issuecomment-2025847025. Though it's specifically for those seeking Open API 3.x standard support, this would probably apply to you as well.
